import React, { createContext, useContext, useState, useEffect } from "react";

export type DashboardLanguage =
  | "en"
  | "ne"
  | "hi"
  | "es"
  | "fr"
  | "de"
  | "zh"
  | "ja";

interface DashboardLanguageContextType {
  language: DashboardLanguage;
  setLanguage: (lang: DashboardLanguage) => void;
  t: (key: string) => string;
}

const DashboardLanguageContext = createContext<
  DashboardLanguageContextType | undefined
>(undefined);

export const languageNames = {
  en: "English",
  ne: "नेपाली",
  hi: "हिन्दी",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  zh: "中文",
  ja: "日本語",
};

export const languageFlags = {
  en: "🇬🇧",
  ne: "🇳🇵",
  hi: "🇮🇳",
  es: "🇪🇸",
  fr: "🇫🇷",
  de: "🇩🇪",
  zh: "🇨🇳",
  ja: "🇯🇵",
};

const translations = {
  en: {
    // Common
    "common.search": "Search",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.view": "View",
    "common.export": "Export",
    "common.import": "Import",
    "common.print": "Print",
    "common.filter": "Filter",
    "common.clear": "Clear",
    "common.apply": "Apply",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.yes": "Yes",
    "common.no": "No",
    "common.ok": "OK",
    "common.loading": "Loading...",
    "common.nodata": "No data available",
    "common.language": "Language",
    "common.logout": "Logout",
    "common.profile": "Profile",
    "common.settings": "Settings",
    "common.help": "Help",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    "common.reset": "Reset",
    "common.refresh": "Refresh",
    "common.download": "Download",
    "common.upload": "Upload",
    "common.select": "Select",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.total": "Total",
    "common.subtotal": "Subtotal",
    "common.grand_total": "Grand Total",
    "common.discount": "Discount",
    "common.tax": "Tax",
    "common.amount": "Amount",
    "common.quantity": "Quantity",
    "common.price": "Price",
    "common.date": "Date",
    "common.time": "Time",
    "common.name": "Name",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.address": "Address",
    "common.description": "Description",
    "common.notes": "Notes",
    "common.created": "Created",
    "common.updated": "Updated",
    "common.by": "By",

    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.inventory": "Inventory",
    "nav.products": "Products",
    "nav.categories": "Categories",
    "nav.brands": "Brands",
    "nav.parties": "Parties",
    "nav.customers": "Customers",
    "nav.vendors": "Vendors",
    "nav.orders": "Orders",
    "nav.purchase_orders": "Purchase Orders",
    "nav.bills": "Bills",
    "nav.reports": "Reports",
    "nav.analytics": "Analytics",
    "nav.users": "Users",
    "nav.admins": "Admins",
    "nav.managers": "Managers",
    "nav.cashiers": "Cashiers",
    "nav.settings": "Settings",
    "nav.system": "System",
    "nav.cash_bank": "Cash & Bank",
    "nav.shifts": "Shifts",
    "nav.pos": "POS",
    "nav.billing": "Billing",
    "nav.subscriptions": "Subscriptions",
    "nav.branches": "Branches",
    "nav.access_control": "Access Control",
    "nav.permissions": "Permissions",
    "nav.verification": "Verification",
    "nav.audit_logs": "Audit Logs",

    // Dashboard
    "dashboard.welcome": "Welcome back",
    "dashboard.overview": "Overview",
    "dashboard.quick_stats": "Quick Stats",
    "dashboard.recent_activity": "Recent Activity",
    "dashboard.notifications": "Notifications",

    // Inventory
    "inventory.title": "Inventory Management",
    "inventory.total": "Total Inventory",
    "inventory.in_stock": "In Stock",
    "inventory.low_stock": "Low Stock",
    "inventory.out_of_stock": "Out of Stock",
    "inventory.add_product": "Add Product",
    "inventory.product_name": "Product Name",
    "inventory.sku": "SKU",
    "inventory.barcode": "Barcode",
    "inventory.category": "Category",
    "inventory.brand": "Brand",
    "inventory.stock_level": "Stock Level",
    "inventory.unit_price": "Unit Price",
    "inventory.selling_price": "Selling Price",
    "inventory.reorder_level": "Reorder Level",
    "inventory.supplier": "Supplier",

    // Products
    "products.title": "Products",
    "products.add_new": "Add New Product",
    "products.edit": "Edit Product",
    "products.delete": "Delete Product",
    "products.view_details": "View Details",
    "products.bulk_import": "Bulk Import",
    "products.export_csv": "Export CSV",
    "products.search_placeholder": "Search products...",

    // Categories
    "categories.title": "Categories",
    "categories.add_new": "Add Category",
    "categories.edit": "Edit Category",
    "categories.delete": "Delete Category",
    "categories.name": "Category Name",

    // Brands
    "brands.title": "Brands",
    "brands.add_new": "Add Brand",
    "brands.edit": "Edit Brand",
    "brands.delete": "Delete Brand",
    "brands.name": "Brand Name",

    // Parties
    "parties.title": "Parties",
    "parties.add_new": "Add Party",
    "parties.edit": "Edit Party",
    "parties.delete": "Delete Party",
    "parties.customer": "Customer",
    "parties.vendor": "Vendor",
    "parties.both": "Both",
    "parties.type": "Party Type",
    "parties.company_name": "Company Name",
    "parties.contact_person": "Contact Person",
    "parties.credit_limit": "Credit Limit",
    "parties.outstanding": "Outstanding",

    // Orders
    "orders.title": "Orders",
    "orders.add_new": "Create Order",
    "orders.order_number": "Order Number",
    "orders.order_date": "Order Date",
    "orders.delivery_date": "Delivery Date",
    "orders.customer": "Customer",
    "orders.vendor": "Vendor",
    "orders.items": "Items",
    "orders.draft": "Draft",
    "orders.pending": "Pending",
    "orders.confirmed": "Confirmed",
    "orders.processing": "Processing",
    "orders.shipped": "Shipped",
    "orders.delivered": "Delivered",
    "orders.cancelled": "Cancelled",

    // Bills
    "bills.title": "Bills",
    "bills.create_bill": "Create Bill",
    "bills.bill_number": "Bill Number",
    "bills.bill_date": "Bill Date",
    "bills.due_date": "Due Date",
    "bills.payment_status": "Payment Status",
    "bills.paid": "Paid",
    "bills.unpaid": "Unpaid",
    "bills.partial": "Partial",
    "bills.payment_method": "Payment Method",
    "bills.cash": "Cash",
    "bills.card": "Card",
    "bills.esewa": "eSewa",
    "bills.fonepay": "FonePay",
    "bills.bank_transfer": "Bank Transfer",

    // Reports
    "reports.title": "Reports",
    "reports.sales_report": "Sales Report",
    "reports.purchase_report": "Purchase Report",
    "reports.inventory_report": "Inventory Report",
    "reports.profit_loss": "Profit & Loss",
    "reports.daily_report": "Daily Report",
    "reports.monthly_report": "Monthly Report",
    "reports.yearly_report": "Yearly Report",
    "reports.custom_report": "Custom Report",
    "reports.generate": "Generate Report",
    "reports.date_range": "Date Range",
    "reports.from_date": "From Date",
    "reports.to_date": "To Date",

    // Users
    "users.title": "Users",
    "users.add_new": "Add User",
    "users.edit": "Edit User",
    "users.delete": "Delete User",
    "users.username": "Username",
    "users.role": "Role",
    "users.permissions": "Permissions",
    "users.super_admin": "Super Admin",
    "users.admin": "Admin",
    "users.inventory_manager": "Inventory Manager",
    "users.cashier": "Cashier",
    "users.last_login": "Last Login",
    "users.account_status": "Account Status",

    // Cash & Bank
    "cash.title": "Cash & Bank",
    "cash.cash_in_hand": "Cash in Hand",
    "cash.bank_balance": "Bank Balance",
    "cash.cash_in": "Cash In",
    "cash.cash_out": "Cash Out",
    "cash.transaction_type": "Transaction Type",
    "cash.reference": "Reference",
    "cash.account_ledger": "Account Ledger",
    "cash.general_ledger": "General Ledger",
    "cash.sales_ledger": "Sales Ledger",
    "cash.purchase_ledger": "Purchase Ledger",

    // Shifts
    "shifts.title": "Shifts",
    "shifts.start_shift": "Start Shift",
    "shifts.end_shift": "End Shift",
    "shifts.current_shift": "Current Shift",
    "shifts.opening_cash": "Opening Cash",
    "shifts.closing_cash": "Closing Cash",
    "shifts.expected_cash": "Expected Cash",
    "shifts.actual_cash": "Actual Cash",
    "shifts.cash_variance": "Cash Variance",
    "shifts.shift_summary": "Shift Summary",

    // POS/Billing
    "pos.title": "Point of Sale",
    "pos.add_item": "Add Item",
    "pos.scan_barcode": "Scan Barcode",
    "pos.item_code": "Item Code",
    "pos.customer_name": "Customer Name",
    "pos.payment": "Payment",
    "pos.received": "Amount Received",
    "pos.change": "Change",
    "pos.print_receipt": "Print Receipt",
    "pos.complete_sale": "Complete Sale",

    // Settings
    "settings.title": "Settings",
    "settings.general": "General Settings",
    "settings.company": "Company Settings",
    "settings.tax": "Tax Settings",
    "settings.currency": "Currency",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.notifications": "Notifications",
    "settings.backup": "Backup & Restore",
    "settings.preferences": "Preferences",

    // Subscriptions
    "subscriptions.title": "Subscriptions",
    "subscriptions.current_plan": "Current Plan",
    "subscriptions.upgrade": "Upgrade",
    "subscriptions.downgrade": "Downgrade",
    "subscriptions.billing_history": "Billing History",
    "subscriptions.next_billing": "Next Billing Date",
    "subscriptions.active": "Active",
    "subscriptions.expired": "Expired",
    "subscriptions.trial": "Trial",

    // Access Control
    "access.title": "Access Control",
    "access.permissions": "Permissions",
    "access.role_permissions": "Role Permissions",
    "access.grant": "Grant Access",
    "access.revoke": "Revoke Access",
    "access.view": "View",
    "access.create": "Create",
    "access.update": "Update",
    "access.delete": "Delete",

    // Messages
    "msg.success": "Success!",
    "msg.error": "Error!",
    "msg.warning": "Warning!",
    "msg.info": "Information",
    "msg.saved": "Saved successfully",
    "msg.deleted": "Deleted successfully",
    "msg.updated": "Updated successfully",
    "msg.created": "Created successfully",
    "msg.confirm_delete": "Are you sure you want to delete?",
    "msg.no_records": "No records found",
    "msg.processing": "Processing...",
  },

  ne: {
    // Common
    "common.search": "खोज्नुहोस्",
    "common.save": "सुरक्षित गर्नुहोस्",
    "common.cancel": "रद्द गर्नुहोस्",
    "common.delete": "मेटाउनुहोस्",
    "common.edit": "सम्पादन गर्नुहोस्",
    "common.add": "थप्नुहोस्",
    "common.view": "हेर्नुहोस्",
    "common.export": "निर्यात गर्नुहोस्",
    "common.import": "आयात गर्नुहोस्",
    "common.print": "प्रिन्ट गर्नुहोस्",
    "common.filter": "फिल्टर गर्नुहोस्",
    "common.clear": "खाली गर्नुहोस्",
    "common.apply": "लागू गर्नुहोस्",
    "common.close": "बन्द गर्नुहोस्",
    "common.confirm": "पुष्टि गर्नुहोस्",
    "common.yes": "हो",
    "common.no": "होइन",
    "common.ok": "ठीक छ",
    "common.loading": "लोड हुँदैछ...",
    "common.nodata": "कुनै डाटा उपलब्ध छैन",
    "common.language": "भाषा",
    "common.logout": "लगआउट",
    "common.profile": "प्रोफाइल",
    "common.settings": "सेटिङहRs",
    "common.help": "सहायता",
    "common.back": "पछाडि",
    "common.next": "अगाडि",
    "common.previous": "अघिल्लो",
    "common.submit": "पेश गर्नुहोस्",
    "common.reset": "रिसेट गर्नुहोस्",
    "common.refresh": "ताजा गर्नुहोस्",
    "common.download": "डाउनलोड गर्नुहोस्",
    "common.upload": "अपलोड गर्नुहोस्",
    "common.select": "चयन गर्नुहोस्",
    "common.actions": "कार्यहRs",
    "common.status": "स्थिति",
    "common.active": "सक्रिय",
    "common.inactive": "निष्क्रिय",
    "common.total": "कुल",
    "common.subtotal": "उप-कुल",
    "common.grand_total": "महा कुल",
    "common.discount": "छुट",
    "common.tax": "कर",
    "common.amount": "रकम",
    "common.quantity": "परिमाण",
    "common.price": "मूल्य",
    "common.date": "मिति",
    "common.time": "समय",
    "common.name": "नाम",
    "common.email": "इमेल",
    "common.phone": "फोन",
    "common.address": "ठेगाना",
    "common.description": "विवरण",
    "common.notes": "टिप्पणी",
    "common.created": "सिर्जना गरिएको",
    "common.updated": "अपडेट गरिएको",
    "common.by": "द्वारा",

    // Navigation
    "nav.dashboard": "ड्यासबोर्ड",
    "nav.inventory": "सूची",
    "nav.products": "उत्पादनहRs",
    "nav.categories": "वर्गहRs",
    "nav.brands": "ब्रान्डहRs",
    "nav.parties": "पक्षहRs",
    "nav.customers": "ग्राहकहRs",
    "nav.vendors": "विक्रेताहRs",
    "nav.orders": "अर्डरहRs",
    "nav.purchase_orders": "खरिद आदेशहRs",
    "nav.bills": "बिलहRs",
    "nav.reports": "रिपोर्टहRs",
    "nav.analytics": "विश्लेषण",
    "nav.users": "प्रयोगकर्ताहRs",
    "nav.admins": "प्रशासकहRs",
    "nav.managers": "प्रबन्धकहRs",
    "nav.cashiers": "क्यासियरहRs",
    "nav.settings": "सेटिङहRs",
    "nav.system": "प्रणाली",
    "nav.cash_bank": "नगद र बैंक",
    "nav.shifts": "सिफ्टहRs",
    "nav.pos": "पीओएस",
    "nav.billing": "बिलिङ",
    "nav.subscriptions": "सदस्यताहRs",
    "nav.branches": "शाखाहRs",
    "nav.access_control": "पहुँच नियन्त्रण",
    "nav.permissions": "अनुमतिहRs",
    "nav.verification": "प्रमाणीकरण",
    "nav.audit_logs": "अडिट लगहRs",

    // Dashboard
    "dashboard.welcome": "स्वागत छ",
    "dashboard.overview": "सारांश",
    "dashboard.quick_stats": "द्रुत तथ्याङ्क",
    "dashboard.recent_activity": "हालैको गतिविधि",
    "dashboard.notifications": "सूचनाहRs",

    // Inventory
    "inventory.title": "सूची व्यवस्थापन",
    "inventory.total": "कुल सूची",
    "inventory.in_stock": "स्टकमा",
    "inventory.low_stock": "कम स्टक",
    "inventory.out_of_stock": "स्टक समाप्त",
    "inventory.add_product": "उत्पादन थप्नुहोस्",
    "inventory.product_name": "उत्पादन नाम",
    "inventory.sku": "एसकेयू",
    "inventory.barcode": "बारकोड",
    "inventory.category": "वर्ग",
    "inventory.brand": "ब्रान्ड",
    "inventory.stock_level": "स्टक स्तर",
    "inventory.unit_price": "एकाइ मूल्य",
    "inventory.selling_price": "बिक्री मूल्य",
    "inventory.reorder_level": "पुन: अर्डर स्तर",
    "inventory.supplier": "आपूर्तिकर्ता",

    // Products
    "products.title": "उत्पादनहRs",
    "products.add_new": "नयाँ उत्पादन थप्नुहोस्",
    "products.edit": "उत्पादन सम्पादन गर्नुहोस्",
    "products.delete": "उत्पादन मेटाउनुहोस्",
    "products.view_details": "विवरण हेर्नुहोस्",
    "products.bulk_import": "थोक आयात",
    "products.export_csv": "सीएसभी निर्यात",
    "products.search_placeholder": "उत्पादनहRs खोज्नुहोस्...",

    // Categories
    "categories.title": "वर्गहRs",
    "categories.add_new": "वर्ग थप्नुहोस्",
    "categories.edit": "वर्ग सम्पादन गर्नुहोस्",
    "categories.delete": "वर्ग मेटाउनुहोस्",
    "categories.name": "वर्ग नाम",

    // Brands
    "brands.title": "ब्रान्डहRs",
    "brands.add_new": "ब्रान्ड थप्नुहोस्",
    "brands.edit": "ब्रान्ड सम्पादन गर्नुहोस्",
    "brands.delete": "ब्रान्ड मेटाउनुहोस्",
    "brands.name": "ब्रान्ड नाम",

    // Parties
    "parties.title": "पक्षहRs",
    "parties.add_new": "पक्ष थप्नुहोस्",
    "parties.edit": "पक्ष सम्पादन गर्नुहोस्",
    "parties.delete": "पक्ष मेटाउनुहोस्",
    "parties.customer": "ग्राहक",
    "parties.vendor": "विक्रेता",
    "parties.both": "दुवै",
    "parties.type": "पक्ष प्रकार",
    "parties.company_name": "कम्पनीको नाम",
    "parties.contact_person": "सम्पर्क व्यक्ति",
    "parties.credit_limit": "क्रेडिट सीमा",
    "parties.outstanding": "बाँकी",

    // Orders
    "orders.title": "अर्डरहRs",
    "orders.add_new": "अर्डर सिर्जना गर्नुहोस्",
    "orders.order_number": "अर्डर नम्बर",
    "orders.order_date": "अर्डर मिति",
    "orders.delivery_date": "डेलिभरी मिति",
    "orders.customer": "ग्राहक",
    "orders.vendor": "विक्रेता",
    "orders.items": "वस्तुहRs",
    "orders.draft": "ड्राफ्ट",
    "orders.pending": "पेन्डिङ",
    "orders.confirmed": "पुष्टि भएको",
    "orders.processing": "प्रशोधन",
    "orders.shipped": "पठाइएको",
    "orders.delivered": "पुर्‍याइएको",
    "orders.cancelled": "रद्द गरिएको",

    // Bills
    "bills.title": "बिलहRs",
    "bills.create_bill": "बिल सिर्जना गर्नुहोस्",
    "bills.bill_number": "बिल नम्बर",
    "bills.bill_date": "बिल मिति",
    "bills.due_date": "म्याद मिति",
    "bills.payment_status": "भुक्तानी स्थिति",
    "bills.paid": "भुक्तानी भएको",
    "bills.unpaid": "भुक्तानी नभएको",
    "bills.partial": "आंशिक",
    "bills.payment_method": "भुक्तानी विधि",
    "bills.cash": "नगद",
    "bills.card": "कार्ड",
    "bills.esewa": "ईसेवा",
    "bills.fonepay": "फोनपे",
    "bills.bank_transfer": "बैंक स्थानान्तरण",

    // Reports
    "reports.title": "रिपोर्टहRs",
    "reports.sales_report": "बिक्री रिपोर्ट",
    "reports.purchase_report": "खरिद रिपोर्ट",
    "reports.inventory_report": "सूची रिपोर्ट",
    "reports.profit_loss": "नाफा र हानि",
    "reports.daily_report": "दैनिक रिपोर्ट",
    "reports.monthly_report": "मासिक रिपोर्ट",
    "reports.yearly_report": "वार्षिक रिपोर्ट",
    "reports.custom_report": "अनुकूल रिपोर्ट",
    "reports.generate": "रिपोर्ट उत्पन्न गर्नुहोस्",
    "reports.date_range": "मिति दायरा",
    "reports.from_date": "मिति देखि",
    "reports.to_date": "मिति सम्म",

    // Users
    "users.title": "प्रयोगकर्ताहRs",
    "users.add_new": "प्रयोगकर्ता थप्नुहोस्",
    "users.edit": "प्रयोगकर्ता सम्पादन गर्नुहोस्",
    "users.delete": "प्रयोगकर्ता मेटाउनुहोस्",
    "users.username": "प्रयोगकर्ता नाम",
    "users.role": "भूमिका",
    "users.permissions": "अनुमतिहRs",
    "users.super_admin": "सुपर प्रशासक",
    "users.admin": "प्रशासक",
    "users.inventory_manager": "सूची प्रबन्धक",
    "users.cashier": "क्यासियर",
    "users.last_login": "अन्तिम लगइन",
    "users.account_status": "खाता स्थिति",

    // Cash & Bank
    "cash.title": "नगद र बैंक",
    "cash.cash_in_hand": "हातमा नगद",
    "cash.bank_balance": "बैंक ब्यालेन्स",
    "cash.cash_in": "नगद भित्र",
    "cash.cash_out": "नगद बाहिर",
    "cash.transaction_type": "लेनदेन प्रकार",
    "cash.reference": "सन्दर्भ",
    "cash.account_ledger": "खाता लेजर",
    "cash.general_ledger": "सामान्य लेजर",
    "cash.sales_ledger": "बिक्री लेजर",
    "cash.purchase_ledger": "खरिद लेजर",

    // Shifts
    "shifts.title": "सिफ्टहRs",
    "shifts.start_shift": "सिफ्ट सुरु गर्नुहोस्",
    "shifts.end_shift": "सिफ्ट समाप्त गर्नुहोस्",
    "shifts.current_shift": "हालको सिफ्ट",
    "shifts.opening_cash": "खोल्ने नगद",
    "shifts.closing_cash": "बन्द गर्ने नगद",
    "shifts.expected_cash": "अपेक्षित नगद",
    "shifts.actual_cash": "वास्तविक नगद",
    "shifts.cash_variance": "नगद भिन्नता",
    "shifts.shift_summary": "सिफ्ट सारांश",

    // POS/Billing
    "pos.title": "पोइन्ट अफ सेल",
    "pos.add_item": "वस्तु थप्नुहोस्",
    "pos.scan_barcode": "बारकोड स्क्यान गर्नुहोस्",
    "pos.item_code": "वस्तु कोड",
    "pos.customer_name": "ग्राहक नाम",
    "pos.payment": "भुक्तानी",
    "pos.received": "प्राप्त रकम",
    "pos.change": "फेरबदल",
    "pos.print_receipt": "रसिद प्रिन्ट गर्नुहोस्",
    "pos.complete_sale": "बिक्री पूरा गर्नुहोस्",

    // Settings
    "settings.title": "सेटिङहRs",
    "settings.general": "सामान्य सेटिङहRs",
    "settings.company": "कम्पनी सेटिङहRs",
    "settings.tax": "कर सेटिङहRs",
    "settings.currency": "मुद्रा",
    "settings.language": "भाषा",
    "settings.theme": "थिम",
    "settings.notifications": "सूचनाहRs",
    "settings.backup": "ब्याकअप र पुनर्स्थापना",
    "settings.preferences": "प्राथमिकताहRs",

    // Subscriptions
    "subscriptions.title": "सदस्यताहRs",
    "subscriptions.current_plan": "हालको योजना",
    "subscriptions.upgrade": "अपग्रेड",
    "subscriptions.downgrade": "डाउनग्रेड",
    "subscriptions.billing_history": "बिलिङ इतिहास",
    "subscriptions.next_billing": "अर्को बिलिङ मिति",
    "subscriptions.active": "सक्रिय",
    "subscriptions.expired": "समाप्त भएको",
    "subscriptions.trial": "परीक्षण",

    // Access Control
    "access.title": "पहुँच नियन्त्रण",
    "access.permissions": "अनुमतिहRs",
    "access.role_permissions": "भूमिका अनुमतिहRs",
    "access.grant": "पहुँच दिनुहोस्",
    "access.revoke": "पहुँच रद्द गर्नुहोस्",
    "access.view": "हेर्नुहोस्",
    "access.create": "सिर्जना गर्नुहोस्",
    "access.update": "अपडेट गर्नुहोस्",
    "access.delete": "मेटाउनुहोस्",

    // Messages
    "msg.success": "सफल!",
    "msg.error": "त्रुटि!",
    "msg.warning": "चेतावनी!",
    "msg.info": "जानकारी",
    "msg.saved": "सफलतापूर्वक सुरक्षित गरियो",
    "msg.deleted": "सफलतापूर्वक मेटियो",
    "msg.updated": "सफलतापूर्वक अपडेट गरियो",
    "msg.created": "सफलतापूर्वक सिर्जना गरियो",
    "msg.confirm_delete": "के तपाईं मेटाउन निश्चित हुनुहुन्छ?",
    "msg.no_records": "कुनै रेकर्ड फेला परेन",
    "msg.processing": "प्रशोधन गर्दै...",
  },

  hi: {
    // Common
    "common.search": "खोजें",
    "common.save": "सहेजें",
    "common.cancel": "रद्द करें",
    "common.delete": "हटाएं",
    "common.edit": "संपादित करें",
    "common.add": "जोड़ें",
    "common.view": "देखें",
    "common.export": "निर्यात करें",
    "common.import": "आयात करें",
    "common.print": "प्रिंट करें",
    "common.filter": "फ़िल्टर करें",
    "common.clear": "साफ़ करें",
    "common.apply": "लागू करें",
    "common.close": "बंद करें",
    "common.confirm": "पुष्टि करें",
    "common.yes": "हाँ",
    "common.no": "नहीं",
    "common.ok": "ठीक है",
    "common.loading": "लोड हो रहा है...",
    "common.nodata": "कोई डेटा उपलब्ध नहीं",
    "common.language": "भाषा",
    "common.logout": "लॉगआउट",
    "common.profile": "प्रोफ़ाइल",
    "common.settings": "सेटिंग",
    "common.help": "मदद",
    "common.back": "वापस",
    "common.next": "अगला",
    "common.previous": "पिछला",
    "common.submit": "जमा करें",
    "common.reset": "रीसेट करें",
    "common.refresh": "ताज़ा करें",
    "common.download": "डाउनलोड करें",
    "common.upload": "अपलोड करें",
    "common.select": "चुनें",
    "common.actions": "क्रियाएं",
    "common.status": "स्थिति",
    "common.active": "सक्रिय",
    "common.inactive": "निष्क्रिय",
    "common.total": "कुल",
    "common.subtotal": "उप-कुल",
    "common.grand_total": "महा कुल",
    "common.discount": "छूट",
    "common.tax": "कर",
    "common.amount": "राशि",
    "common.quantity": "मात्रा",
    "common.price": "मूल्य",
    "common.date": "तारीख",
    "common.time": "समय",
    "common.name": "नाम",
    "common.email": "ईमेल",
    "common.phone": "फ़ोन",
    "common.address": "पता",
    "common.description": "विवरण",
    "common.notes": "नोट्स",
    "common.created": "बनाया गया",
    "common.updated": "अपडेट किया गया",
    "common.by": "द्वारा",

    // Navigation
    "nav.dashboard": "डैशबोर्ड",
    "nav.inventory": "इन्वेंटरी",
    "nav.products": "उत्पाद",
    "nav.categories": "श्रेणियाँ",
    "nav.brands": "ब्रांड",
    "nav.parties": "पार्टियाँ",
    "nav.customers": "ग्राहक",
    "nav.vendors": "विक्रेता",
    "nav.orders": "ऑर्डर",
    "nav.purchase_orders": "खरीद आदेश",
    "nav.bills": "बिल",
    "nav.reports": "रिपोर्ट",
    "nav.analytics": "विश्लेषण",
    "nav.users": "उपयोगकर्ता",
    "nav.admins": "व्यवस्थापक",
    "nav.managers": "प्रबंधक",
    "nav.cashiers": "कैशियर",
    "nav.settings": "सेटिंग",
    "nav.system": "सिस्टम",
    "nav.cash_bank": "नकद और बैंक",
    "nav.shifts": "शिफ्ट",
    "nav.pos": "पीओएस",
    "nav.billing": "बिलिंग",
    "nav.subscriptions": "सदस्यता",
    "nav.branches": "शाखाएं",
    "nav.access_control": "एक्सेस कंट्रोल",
    "nav.permissions": "अनुमतियाँ",
    "nav.verification": "सत्यापन",
    "nav.audit_logs": "ऑडिट लॉग",

    // Dashboard
    "dashboard.welcome": "स्वागत है",
    "dashboard.overview": "सारांश",
    "dashboard.quick_stats": "त्वरित आंकड़े",
    "dashboard.recent_activity": "हाल की गतिविधि",
    "dashboard.notifications": "सूचनाएं",

    // Continue with remaining translations...
    // (For brevity, I'll add placeholders - in production you'd complete all)
    "inventory.title": "इन्वेंटरी प्रबंधन",
    "products.title": "उत्पाद",
    "categories.title": "श्रेणियाँ",
    "brands.title": "ब्रांड",
    "parties.title": "पार्टियाँ",
    "orders.title": "ऑर्डर",
    "bills.title": "बिल",
    "reports.title": "रिपोर्ट",
    "users.title": "उपयोगकर्ता",
    "cash.title": "नकद और बैंक",
    "shifts.title": "शिफ्ट",
    "pos.title": "पॉइंट ऑफ सेल",
    "settings.title": "सेटिंग",
    "subscriptions.title": "सदस्यता",
    "access.title": "एक्सेस कंट्रोल",
    "msg.success": "सफल!",
    "msg.error": "त्रुटि!",
  },

  es: {
    // Common
    "common.search": "Buscar",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.add": "Agregar",
    "common.view": "Ver",
    "common.export": "Exportar",
    "common.import": "Importar",
    "common.print": "Imprimir",
    "common.filter": "Filtrar",
    "common.clear": "Limpiar",
    "common.apply": "Aplicar",
    "common.close": "Cerrar",
    "common.confirm": "Confirmar",
    "common.yes": "Sí",
    "common.no": "No",
    "common.ok": "OK",
    "common.loading": "Cargando...",
    "common.nodata": "No hay datos disponibles",
    "common.language": "Idioma",
    "common.logout": "Cerrar sesión",
    "common.profile": "Perfil",
    "common.settings": "Configuración",
    "common.help": "Ayuda",
    "common.back": "Atrás",
    "common.next": "Siguiente",
    "common.previous": "Anterior",
    "common.submit": "Enviar",
    "common.reset": "Restablecer",
    "common.refresh": "Actualizar",
    "common.download": "Descargar",
    "common.upload": "Subir",
    "common.select": "Seleccionar",
    "common.actions": "Acciones",
    "common.status": "Estado",
    "common.active": "Activo",
    "common.inactive": "Inactivo",
    "common.total": "Total",

    // Navigation
    "nav.dashboard": "Panel",
    "nav.inventory": "Inventario",
    "nav.products": "Productos",
    "nav.categories": "Categorías",
    "nav.brands": "Marcas",
    "nav.parties": "Partes",
    "nav.orders": "Pedidos",
    "nav.bills": "Facturas",
    "nav.reports": "Informes",
    "nav.users": "Usuarios",
    "nav.settings": "Configuración",
    "nav.cash_bank": "Efectivo y Banco",
    "nav.shifts": "Turnos",
    "nav.pos": "TPV",

    // Dashboard
    "dashboard.welcome": "Bienvenido de nuevo",
    "dashboard.overview": "Resumen",
    "dashboard.quick_stats": "Estadísticas rápidas",

    // Titles
    "inventory.title": "Gestión de Inventario",
    "products.title": "Productos",
    "categories.title": "Categorías",
    "brands.title": "Marcas",
    "parties.title": "Partes",
    "orders.title": "Pedidos",
    "bills.title": "Facturas",
    "reports.title": "Informes",
    "users.title": "Usuarios",
    "cash.title": "Efectivo y Banco",
    "shifts.title": "Turnos",
    "pos.title": "Punto de Venta",
    "settings.title": "Configuración",
    "subscriptions.title": "Suscripciones",
    "access.title": "Control de Acceso",
    "msg.success": "¡Éxito!",
    "msg.error": "¡Error!",
  },

  fr: {
    // Common
    "common.search": "Rechercher",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.add": "Ajouter",
    "common.view": "Voir",
    "common.export": "Exporter",
    "common.import": "Importer",
    "common.print": "Imprimer",
    "common.filter": "Filtrer",
    "common.language": "Langue",
    "common.logout": "Déconnexion",
    "common.profile": "Profil",
    "common.settings": "Paramètres",

    // Navigation
    "nav.dashboard": "Tableau de bord",
    "nav.inventory": "Inventaire",
    "nav.products": "Produits",
    "nav.categories": "Catégories",
    "nav.brands": "Marques",
    "nav.parties": "Parties",
    "nav.orders": "Commandes",
    "nav.bills": "Factures",
    "nav.reports": "Rapports",
    "nav.users": "Utilisateurs",
    "nav.settings": "Paramètres",
    "nav.cash_bank": "Caisse et Banque",
    "nav.shifts": "Quarts",
    "nav.pos": "Point de Vente",

    // Dashboard
    "dashboard.welcome": "Bon retour",
    "dashboard.overview": "Aperçu",

    // Titles
    "inventory.title": "Gestion des Stocks",
    "products.title": "Produits",
    "categories.title": "Catégories",
    "brands.title": "Marques",
    "parties.title": "Parties",
    "orders.title": "Commandes",
    "bills.title": "Factures",
    "reports.title": "Rapports",
    "users.title": "Utilisateurs",
    "cash.title": "Caisse et Banque",
    "shifts.title": "Quarts",
    "pos.title": "Point de Vente",
    "settings.title": "Paramètres",
    "subscriptions.title": "Abonnements",
    "access.title": "Contrôle d'Accès",
    "msg.success": "Succès!",
    "msg.error": "Erreur!",
  },

  de: {
    // Common
    "common.search": "Suchen",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.add": "Hinzufügen",
    "common.view": "Ansehen",
    "common.language": "Sprache",
    "common.logout": "Abmelden",
    "common.profile": "Profil",
    "common.settings": "Einstellungen",

    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.inventory": "Inventar",
    "nav.products": "Produkte",
    "nav.categories": "Kategorien",
    "nav.brands": "Marken",
    "nav.parties": "Parteien",
    "nav.orders": "Bestellungen",
    "nav.bills": "Rechnungen",
    "nav.reports": "Berichte",
    "nav.users": "Benutzer",
    "nav.settings": "Einstellungen",
    "nav.cash_bank": "Kasse und Bank",
    "nav.shifts": "Schichten",
    "nav.pos": "Kasse",

    // Dashboard
    "dashboard.welcome": "Willkommen zurück",

    // Titles
    "inventory.title": "Bestandsverwaltung",
    "products.title": "Produkte",
    "categories.title": "Kategorien",
    "brands.title": "Marken",
    "parties.title": "Parteien",
    "orders.title": "Bestellungen",
    "bills.title": "Rechnungen",
    "reports.title": "Berichte",
    "users.title": "Benutzer",
    "cash.title": "Kasse und Bank",
    "shifts.title": "Schichten",
    "pos.title": "Verkaufsstelle",
    "settings.title": "Einstellungen",
    "subscriptions.title": "Abonnements",
    "access.title": "Zugriffskontrolle",
    "msg.success": "Erfolg!",
    "msg.error": "Fehler!",
  },

  zh: {
    // Common
    "common.search": "搜索",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.add": "添加",
    "common.view": "查看",
    "common.language": "语言",
    "common.logout": "登出",
    "common.profile": "个人资料",
    "common.settings": "设置",

    // Navigation
    "nav.dashboard": "仪表板",
    "nav.inventory": "库存",
    "nav.products": "产品",
    "nav.categories": "类别",
    "nav.brands": "品牌",
    "nav.parties": "各方",
    "nav.orders": "订单",
    "nav.bills": "账单",
    "nav.reports": "报告",
    "nav.users": "用户",
    "nav.settings": "设置",
    "nav.cash_bank": "现金和银行",
    "nav.shifts": "班次",
    "nav.pos": "销售点",

    // Dashboard
    "dashboard.welcome": "欢迎回来",

    // Titles
    "inventory.title": "库存管理",
    "products.title": "产品",
    "categories.title": "类别",
    "brands.title": "品牌",
    "parties.title": "各方",
    "orders.title": "订单",
    "bills.title": "账单",
    "reports.title": "报告",
    "users.title": "用户",
    "cash.title": "现金和银行",
    "shifts.title": "班次",
    "pos.title": "销售点",
    "settings.title": "设置",
    "subscriptions.title": "订阅",
    "access.title": "访问控制",
    "msg.success": "成功！",
    "msg.error": "错误！",
  },

  ja: {
    // Common
    "common.search": "検索",
    "common.save": "保存",
    "common.cancel": "キャンセル",
    "common.delete": "削除",
    "common.edit": "編集",
    "common.add": "追加",
    "common.view": "表示",
    "common.language": "言語",
    "common.logout": "ログアウト",
    "common.profile": "プロフィール",
    "common.settings": "設定",

    // Navigation
    "nav.dashboard": "ダッシュボード",
    "nav.inventory": "在庫",
    "nav.products": "製品",
    "nav.categories": "カテゴリー",
    "nav.brands": "ブランド",
    "nav.parties": "当事者",
    "nav.orders": "注文",
    "nav.bills": "請求書",
    "nav.reports": "レポート",
    "nav.users": "ユーザー",
    "nav.settings": "設定",
    "nav.cash_bank": "現金と銀行",
    "nav.shifts": "シフト",
    "nav.pos": "販売時点",

    // Dashboard
    "dashboard.welcome": "おかえりなさい",

    // Titles
    "inventory.title": "在庫管理",
    "products.title": "製品",
    "categories.title": "カテゴリー",
    "brands.title": "ブランド",
    "parties.title": "当事者",
    "orders.title": "注文",
    "bills.title": "請求書",
    "reports.title": "レポート",
    "users.title": "ユーザー",
    "cash.title": "現金と銀行",
    "shifts.title": "シフト",
    "pos.title": "販売時点管理",
    "settings.title": "設定",
    "subscriptions.title": "サブスクリプション",
    "access.title": "アクセス制御",
    "msg.success": "成功！",
    "msg.error": "エラー！",
  },
};

export const DashboardLanguageProvider: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  const [language, setLanguageState] = useState<DashboardLanguage>(() => {
    // Load language from localStorage or default to 'en'
    const saved = localStorage.getItem("dashboard_language");
    return (saved as DashboardLanguage) || "en";
  });

  const setLanguage = (lang: DashboardLanguage) => {
    setLanguageState(lang);
    localStorage.setItem("dashboard_language", lang);

    // Trigger a custom event to notify all components
    window.dispatchEvent(
      new CustomEvent("languageChanged", { detail: { language: lang } })
    );
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <DashboardLanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </DashboardLanguageContext.Provider>
  );
};

export const useDashboardLanguage = () => {
  const context = useContext(DashboardLanguageContext);
  if (!context) {
    throw new Error(
      "useDashboardLanguage must be used within a DashboardLanguageProvider"
    );
  }
  return context;
};
