import React, { createContext, useContext, useState } from 'react';

type LandingLanguage = 'en' | 'ne';

interface LandingLanguageContextType {
  language: LandingLanguage;
  setLanguage: (lang: LandingLanguage) => void;
  t: (key: string) => string;
}

const LandingLanguageContext = createContext<LandingLanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'nav.blog': 'Blog',
    'nav.login': 'Login',
    
    // Home Page
    'home.badge': '🔧 #1 Auto Parts Management System',
    'home.title1': 'Manage Your',
    'home.title2': 'Auto Parts',
    'home.title3': 'Inventory Smart',
    'home.subtitle': 'Complete inventory management solution for two-wheelers and four-wheelers. Track parts, manage orders, handle billing - all in one powerful system.',
    'home.getStarted': 'Get Started Now',
    'home.learnMore': 'Learn More',
    'home.stats1': 'Active Users',
    'home.stats2': 'Uptime',
    'home.stats3': 'Support',
    'home.floatingCard1': 'Multi-Role Access',
    'home.floatingCard2': 'Real-Time Sync',
    'home.heroTagline1': 'Your Inventory,',
    'home.heroTagline2': 'Fully Automated',
    
    // Features
    'features.badge': 'Features',
    'features.title': 'Everything You Need',
    'features.subtitle': 'Powerful features designed specifically for auto parts inventory management',
    'feature.inventory.title': 'Inventory Tracking',
    'feature.inventory.desc': 'Track two-wheeler and four-wheeler parts with barcode scanning and real-time updates',
    'feature.analytics.title': 'Advanced Analytics',
    'feature.analytics.desc': 'Comprehensive reports and insights to make data-driven business decisions',
    'feature.multirole.title': 'Multi-Role System',
    'feature.multirole.desc': 'Super Admin, Admin, Manager, Cashier, and Finance roles with custom permissions',
    'feature.billing.title': 'Billing & Orders',
    'feature.billing.desc': 'Complete order management with NPR currency, eSewa, and FonePay integration',
    'feature.supplier.title': 'Supplier Management',
    'feature.supplier.desc': 'Manage vendors, track purchases, and handle multi-vendor operations',
    'feature.secure.title': 'Secure & Reliable',
    'feature.secure.desc': 'Bank-level security with real-time permission sync and data protection',
    
    // Stats
    'stats.parts': 'Parts Tracked',
    'stats.roles': 'User Roles',
    'stats.languages': 'Languages',
    'stats.sync': 'Real-Time Sync',
    
    // How It Works
    'howitworks.badge': 'How It Works',
    'howitworks.title': 'Get Started in 4 Simple Steps',
    'howitworks.subtitle': 'Start managing your auto parts inventory in minutes',
    'howitworks.step1.title': 'Register & Login',
    'howitworks.step1.desc': 'Create your account or login with existing credentials',
    'howitworks.step2.title': 'Set Up Inventory',
    'howitworks.step2.desc': 'Add your parts, categories, and pricing information',
    'howitworks.step3.title': 'Manage Operations',
    'howitworks.step3.desc': 'Track orders, handle billing, and manage your team',
    'howitworks.step4.title': 'Grow Your Business',
    'howitworks.step4.desc': 'Use analytics and insights to make better decisions',
    
    // Testimonials
    'testimonials.badge': 'Testimonials',
    'testimonials.title': 'What Our Users Say',
    'testimonials.subtitle': 'Trusted by businesses across Nepal',
    'testimonials.1.text': 'Serve Spares transformed how we manage our parts inventory. The multi-language support is excellent!',
    'testimonials.1.name': 'Rajesh Kumar',
    'testimonials.1.role': 'Shop Owner, Kathmandu',
    'testimonials.2.text': 'Real-time sync and barcode scanning made our operations so much faster. Highly recommended!',
    'testimonials.2.name': 'Sita Sharma',
    'testimonials.2.role': 'Inventory Manager',
    'testimonials.3.text': 'The permission system is perfect. Each staff member has exactly the access they need.',
    'testimonials.3.name': 'Anil Thapa',
    'testimonials.3.role': 'Business Owner',
    
    // CTA
    'cta.title': 'Ready to Transform Your Inventory?',
    'cta.subtitle': 'Join hundreds of businesses already using Serve Spares',
    
    // Footer
    'footer.description': 'Complete inventory management solution for two-wheelers and four-wheelers with multi-role access, real-time sync, and comprehensive features.',
    'footer.quicklinks': 'Quick Links',
    'footer.plans': 'Plans',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.contact': 'Contact',
    'footer.features': 'Features',
    'footer.howitworks': 'How It Works',
    'footer.reviews': 'Reviews',
    'footer.about': 'About Us',
    'footer.blog': 'Blog',
    'footer.pricing': 'Pricing',
    'footer.faq': 'FAQ',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.contactus': 'Contact Us',
    'footer.email': 'support@servespares.com',
    'footer.phone': '+977 1234567890',
    'footer.address': 'Kathmandu, Nepal',
    'footer.hours': '24/7 Support',
    'footer.copyright': 'All rights reserved.',
    'footer.secure': 'Secure',
    'footer.reliable': 'Reliable',
    'footer.fast': 'Fast',
    'footer.blog.title': 'Explore Our Blog',
    'footer.blog.subtitle': 'Discover insightful articles and tips to elevate your business journey.',
    'footer.blog.readmore': 'Read More',
    'footer.app.title': 'Connect & Manage on a Touch !',
    'footer.app.subtitle': 'Track inventory, Streamline tasks, Ensure smooth mobile app. Add property, Manage Sales, Track your overall performance, and access all your properties directly from your phone or tablet.',
    'footer.app.tagline': 'A PERFECT PARTNER FOR YOU AND YOUR AUTO PARTS BUSINESS',
    'footer.app.cta': 'Get Started with Us',
    'footer.follow': 'Follow us on social media',
    
    // About Page
    'about.title': 'About Serve Spares',
    'about.subtitle': 'Revolutionizing auto parts inventory management for two-wheelers and four-wheelers across Nepal and beyond.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To empower auto parts businesses with cutting-edge inventory management technology that simplifies operations, enhances customer service, and drives sustainable growth.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To become the leading inventory management solution for auto parts businesses, making efficient spare parts management accessible to shops of all sizes across South Asia.',
    'about.story.title': 'Our Story',
    'about.story.p1': 'Founded in 2023, Serve Spares was born from a simple observation: auto parts shop owners in Nepal were struggling with outdated inventory systems that couldn\'t keep up with their growing businesses.',
    'about.story.p2': 'Our founders, experienced entrepreneurs in the automotive industry, assembled a team of talented developers and industry experts to create a platform specifically designed for two-wheeler and four-wheeler parts management. We understood the unique challenges - from managing thousands of SKUs to handling multiple vendors and locations.',
    'about.story.p3': 'Today, we\'re proud to serve businesses across Nepal and expanding throughout South Asia. Our platform supports multi-role access, real-time synchronization, barcode scanning, and comprehensive order management - all tailored for the Nepali market with NPR currency, local payment methods like eSewa and FonePay, and multi-language support.',
    'about.values.title': 'Our Core Values',
    'about.values.subtitle': 'These principles guide everything we do and shape our commitment to you.',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'Constantly evolving with cutting-edge technology for auto parts management.',
    'about.values.customer': 'Customer First',
    'about.values.customer.desc': 'Your success is our success. We listen, adapt, and deliver.',
    'about.values.reliability': 'Reliability',
    'about.values.reliability.desc': '99.9% uptime with bank-level security you can depend on.',
    'about.values.local': 'Local Focus',
    'about.values.local.desc': 'Built for Nepal with NPR, eSewa, FonePay, and local language support.',
    'about.values.scalability': 'Scalability',
    'about.values.scalability.desc': 'From single shop to multi-branch operations, we grow with you.',
    'about.values.efficiency': 'Efficiency',
    'about.values.efficiency.desc': 'Streamlined workflows that save time and increase profits.',
    'about.stats.users': 'Active Users',
    'about.stats.parts': 'Parts Tracked',
    'about.stats.uptime': 'Uptime SLA',
    'about.stats.support': 'Support',
    
    // Features Page
    'features.title': 'Powerful Features',
    'features.subtitle': 'Everything you need to manage your auto parts inventory efficiently and profitably.',
    'features.core.badge': 'Core Features',
    'features.core.title': 'Everything You Need',
    'features.core.subtitle': 'Comprehensive tools designed specifically for auto parts inventory management.',
    'features.inventory.title': 'Inventory Management',
    'features.inventory.desc': 'Complete parts tracking for two-wheelers and four-wheelers with real-time stock updates.',
    'features.inventory.f1': 'Multi-category support',
    'features.inventory.f2': 'Stock level tracking',
    'features.inventory.f3': 'Low stock alerts',
    'features.inventory.f4': 'Part number search',
    'features.barcode.title': 'Barcode Scanning',
    'features.barcode.desc': 'Bulk barcode scanning system for quick inventory updates and order processing.',
    'features.barcode.f1': 'Bulk import/export',
    'features.barcode.f2': 'Scan to search',
    'features.barcode.f3': 'Quick billing',
    'features.barcode.f4': 'Inventory updates',
    'features.orders.title': 'Order Management',
    'features.orders.desc': '7-stage order lifecycle with complete customer and supplier tracking.',
    'features.orders.f1': 'Draft to delivered',
    'features.orders.f2': 'Customer orders',
    'features.orders.f3': 'Supplier orders',
    'features.orders.f4': 'Order history',
    'features.billing.title': 'Billing System',
    'features.billing.desc': 'Comprehensive billing with NPR currency and local payment integrations.',
    'features.billing.f1': 'eSewa integration',
    'features.billing.f2': 'FonePay support',
    'features.billing.f3': 'Invoice generation',
    'features.billing.f4': 'Payment tracking',
    'features.roles.title': 'Multi-Role Access',
    'features.roles.desc': '5 user roles with hierarchical permissions and real-time sync.',
    'features.roles.f1': 'Super Admin',
    'features.roles.f2': 'Admin',
    'features.roles.f3': 'Inventory Manager',
    'features.roles.f4': 'Cashier',
    'features.roles.f5': 'Finance',
    'features.analytics.title': 'Analytics & Reports',
    'features.analytics.desc': 'Comprehensive business insights and data-driven decision making tools.',
    'features.analytics.f1': 'Sales reports',
    'features.analytics.f2': 'Inventory analytics',
    'features.analytics.f3': 'Profit tracking',
    'features.analytics.f4': 'Performance metrics',
    'features.categories.title': 'Feature Categories',
    'features.categories.subtitle': 'Organized tools for every aspect of your auto parts business.',
    'features.cat1.title': 'Inventory Control',
    'features.cat1.f1': 'Product Categories',
    'features.cat1.f2': 'SKU Management',
    'features.cat1.f3': 'Stock Tracking',
    'features.cat1.f4': 'Warehouse Management',
    'features.cat1.f5': 'Reorder Levels',
    'features.cat1.f6': 'Inventory Reports',
    'features.cat2.title': 'Customer & Vendor',
    'features.cat2.f1': 'Party Management',
    'features.cat2.f2': 'Customer Profiles',
    'features.cat2.f3': 'Supplier Database',
    'features.cat2.f4': 'Credit Management',
    'features.cat2.f5': 'Purchase History',
    'features.cat2.f6': 'Vendor Performance',
    'features.cat3.title': 'Branch Operations',
    'features.cat3.f1': 'Multi-Branch Support',
    'features.cat3.f2': 'Branch Analytics',
    'features.cat3.f3': 'Stock Transfer',
    'features.cat3.f4': 'Branch Permissions',
    'features.cat3.f5': 'Location Tracking',
    'features.cat3.f6': 'Centralized Control',
    'features.cat4.title': 'Multi-Language',
    'features.cat4.f1': 'English',
    'features.cat4.f2': 'Nepali',
    'features.cat4.f3': 'Hindi',
    'features.cat4.f4': 'Spanish',
    'features.cat4.f5': 'French',
    'features.cat4.f6': 'German',
    'features.cat4.f7': 'Chinese',
    'features.cat4.f8': 'Japanese',
    'features.technical.badge': 'Technical Excellence',
    'features.technical.title': 'Advanced Technology',
    'features.technical.subtitle': 'Built with modern technology for maximum performance and reliability.',
    'features.tech1.title': 'Real-Time Sync',
    'features.tech1.desc': 'Instant permission and language updates across all users',
    'features.tech2.title': '8 Languages',
    'features.tech2.desc': 'Complete multi-language support with flag-based UI',
    'features.tech3.title': 'Access Control',
    'features.tech3.desc': 'Hierarchical permission system with SuperAdmin protection',
    'features.tech4.title': 'Responsive Design',
    'features.tech4.desc': 'Works perfectly on desktop, tablet, and mobile devices',
    'features.tech5.title': 'Custom Alerts',
    'features.tech5.desc': 'Beautiful branded dialog system instead of default alerts',
    'features.tech6.title': 'Customizable',
    'features.tech6.desc': 'Tailor the system to your specific business needs',
    'features.security.title': 'Enterprise-Grade Security',
    'features.security.subtitle': 'Your business data and customer information are protected with the highest security standards.',
    'features.security1.title': 'Bank-Level Encryption',
    'features.security1.desc': 'All data encrypted with industry-standard protocols',
    'features.security2.title': '99.9% Uptime',
    'features.security2.desc': 'Reliable service you can count on every day',
    'features.security3.title': 'Local & Secure',
    'features.security3.desc': 'Data stored securely with local compliance',
    'features.security4.title': 'Real-time Backup',
    'features.security4.desc': 'Your data is continuously backed up and protected',
    
    // Pricing Page
    'pricing.title': 'Simple, Transparent Pricing',
    'pricing.subtitle': 'Choose the perfect plan for your auto parts business. No hidden fees, cancel anytime.',
    'pricing.monthly': 'Monthly',
    'pricing.yearly': 'Yearly',
    'pricing.save': 'Save 20%',
    'pricing.popular': 'Most Popular',
    'pricing.getstarted': 'Get Started',
    'pricing.plan.starter': 'Starter',
    'pricing.plan.professional': 'Professional',
    'pricing.plan.enterprise': 'Enterprise',
    'pricing.starter.desc': 'Perfect for small auto parts shops just getting started',
    'pricing.professional.desc': 'For growing businesses that need more power',
    'pricing.enterprise.desc': 'For large operations with custom needs',
    'pricing.month': 'month',
    'pricing.year': 'year',
    'pricing.save.yearly': 'Save NPR',
    'pricing.peryear': '/year',
    'pricing.starter.f1': 'Up to 1,000 parts',
    'pricing.starter.f2': 'Single location',
    'pricing.starter.f3': 'Basic inventory tracking',
    'pricing.starter.f4': 'Order management',
    'pricing.starter.f5': 'Email support',
    'pricing.starter.f6': '2 user accounts',
    'pricing.starter.f7': 'Barcode scanning',
    'pricing.starter.f8': 'Multi-branch',
    'pricing.starter.f9': 'Advanced analytics',
    'pricing.professional.f1': 'Up to 10,000 parts',
    'pricing.professional.f2': 'Up to 3 locations',
    'pricing.professional.f3': 'Advanced inventory',
    'pricing.professional.f4': 'Order management',
    'pricing.professional.f5': 'Priority support',
    'pricing.professional.f6': '5 user accounts',
    'pricing.professional.f7': 'Barcode scanning',
    'pricing.professional.f8': 'Analytics & reports',
    'pricing.professional.f9': 'Multi-language',
    'pricing.enterprise.f1': 'Unlimited parts',
    'pricing.enterprise.f2': 'Unlimited locations',
    'pricing.enterprise.f3': 'Full inventory suite',
    'pricing.enterprise.f4': 'Advanced order system',
    'pricing.enterprise.f5': '24/7 phone support',
    'pricing.enterprise.f6': 'Unlimited users',
    'pricing.enterprise.f7': 'Barcode scanning',
    'pricing.enterprise.f8': 'Custom analytics',
    'pricing.enterprise.f9': 'API access',
    'pricing.enterprise.f10': 'Dedicated account manager',
    'pricing.enterprise.f11': 'Custom training',
    'pricing.faq.title': 'Frequently Asked Questions',
    'pricing.faq.subtitle': 'Everything you need to know about our pricing',
    'pricing.faq.q1': 'Can I change my plan later?',
    'pricing.faq.a1': 'Yes! You can upgrade or downgrade your plan at any time. Changes take effect immediately.',
    'pricing.faq.q2': 'What payment methods do you accept?',
    'pricing.faq.a2': 'We accept all major payment methods including eSewa, FonePay, credit/debit cards, and bank transfers.',
    'pricing.faq.q3': 'Is there a free trial?',
    'pricing.faq.a3': 'Yes! We offer a 14-day free trial on all plans. No credit card required to start.',
    'pricing.faq.q4': 'Can I cancel anytime?',
    'pricing.faq.a4': 'Absolutely. You can cancel your subscription at any time. No questions asked, no penalties.',
    'pricing.faq.q5': 'Do you offer discounts for annual billing?',
    'pricing.faq.a5': 'Yes! Save 20% when you choose annual billing. That\'s like getting 2+ months free!',
    'pricing.faq.q6': 'Is training included?',
    'pricing.faq.a6': 'All plans include video tutorials and documentation. Enterprise plans include custom training sessions.',
    'pricing.cta.title': 'Ready to Get Started?',
    'pricing.cta.subtitle': 'Join hundreds of auto parts businesses using Serve Spares',
    'pricing.cta.button': 'Start Free Trial',
    
    // Contact Page
    'contact.title': 'Get In Touch',
    'contact.subtitle': 'Have questions about Serve Spares? We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
    'contact.form.title': 'Send us a Message',
    'contact.form.subtitle': 'Fill out the form below and our team will get back to you shortly.',
    'contact.name': 'Full Name',
    'contact.name.placeholder': 'Ram Bahadur',
    'contact.email': 'Email Address',
    'contact.email.placeholder': 'ram@example.com',
    'contact.phone': 'Phone Number',
    'contact.phone.placeholder': '+977 9876543210',
    'contact.company': 'Shop/Company Name',
    'contact.company.placeholder': 'ABC Auto Parts',
    'contact.message': 'Message',
    'contact.message.placeholder': 'Tell us about your auto parts business and how we can help...',
    'contact.send': 'Send Message',
    'contact.success': '✓ Thank you! We\'ll get back to you within 24 hours.',
    'contact.info.title': 'Contact Information',
    'contact.info.email': 'Email Us',
    'contact.info.email.value': 'support@servespares.com',
    'contact.info.email.sub': 'We reply within 24 hours',
    'contact.info.phone': 'Call Us',
    'contact.info.phone.value': '+977 1234567890',
    'contact.info.phone.sub': 'Mon-Sat, 9AM-6PM NST',
    'contact.info.visit': 'Visit Us',
    'contact.info.visit.value': 'Thamel, Kathmandu',
    'contact.info.visit.sub': 'Nepal',
    'contact.map.title': 'Kathmandu, Nepal',
    'contact.map.subtitle': 'Serving auto parts shops nationwide',
    'contact.locations.title': 'Our Presence in Nepal',
    'contact.locations.subtitle': 'Supporting auto parts businesses across the country.',
    'contact.location.kathmandu': 'Kathmandu',
    'contact.location.kathmandu.region': 'Central Nepal',
    'contact.location.kathmandu.address': 'Thamel, Kathmandu 44600',
    'contact.location.pokhara': 'Pokhara',
    'contact.location.pokhara.region': 'Western Nepal',
    'contact.location.pokhara.address': 'Lakeside, Pokhara',
    'contact.location.biratnagar': 'Biratnagar',
    'contact.location.biratnagar.region': 'Eastern Nepal',
    'contact.location.biratnagar.address': 'Main Road, Biratnagar',
    'contact.location.bharatpur': 'Bharatpur',
    'contact.location.bharatpur.region': 'Central Nepal',
    'contact.location.bharatpur.address': 'Pulchowk, Bharatpur',
    'contact.support.title': 'Need Help?',
    'contact.support.subtitle': 'Multiple ways to get the support you need, when you need it.',
    'contact.support.chat': 'Live Chat',
    'contact.support.chat.desc': 'Chat with our support team in real-time during business hours',
    'contact.support.chat.action': 'Start Chat',
    'contact.support.email': 'Email Support',
    'contact.support.email.desc': 'Send us an email and get a response within 24 hours',
    'contact.support.email.action': 'Send Email',
    'contact.support.help': 'Help Center',
    'contact.support.help.desc': 'Browse our comprehensive documentation and video tutorials',
    'contact.support.help.action': 'Visit Help Center',
    'contact.support.forum': 'Community Forum',
    'contact.support.forum.desc': 'Connect with other auto parts shop owners using Serve Spares',
    'contact.support.forum.action': 'Join Forum',
  },
  ne: {
    // Navigation
    'nav.home': 'होम',
    'nav.about': 'हाम्रो बारेमा',
    'nav.features': 'विशेषताहरू',
    'nav.pricing': 'मूल्य निर्धारण',
    'nav.contact': 'सम्पर्क',
    'nav.blog': 'ब्लग',
    'nav.login': 'लगइन',
    
    // Home Page
    'home.badge': '🔧 #१ अटो पार्ट्स व्यवस्थापन प्रणाली',
    'home.title1': 'आफ्नो',
    'home.title2': 'अटो पार्ट्स',
    'home.title3': 'सूची व्यवस्थापन गर्नुहोस्',
    'home.subtitle': 'दुई-पाङ्ग्रे र चार-पाङ्ग्रे सवारी साधनका लागि पूर्ण सूची व्यवस्थापन समाधान। पार्ट्स ट्रयाक गर्नुहोस्, अर्डर व्यवस्थापन गर्नुहोस्, बिलिङ ह्यान्डल गर्नुहोस् - सबै एउटै शक्तिशाली प्रणालीमा।',
    'home.getStarted': 'अहिले सुरु गर्नुहोस्',
    'home.learnMore': 'थप जान्नुहोस्',
    'home.stats1': 'सक्रिय प्रयोगकर्ता',
    'home.stats2': 'अपटाइम',
    'home.stats3': 'समर्थन',
    'home.floatingCard1': 'बहु-भूमिका पहुँच',
    'home.floatingCard2': 'वास्तविक समय सिङ्क',
    'home.heroTagline1': 'तपाईंको सूची,',
    'home.heroTagline2': 'पूर्ण स्वचालित',
    
    // Features
    'features.badge': 'विशेषताहरू',
    'features.title': 'तपाईंलाई चाहिने सबै कुरा',
    'features.subtitle': 'अटो पार्ट्स सूची व्यवस्थापनको लागि विशेष रूपमा डिजाइन गरिएका शक्तिशाली सुविधाहरू',
    'feature.inventory.title': 'सूची ट्र्याकिङ',
    'feature.inventory.desc': 'बारकोड स्क्यानिङ र वास्तविक समय अपडेटको साथ दुई-पाङ्ग्रे र चार-पाङ्ग्रे पार्ट्स ट्र्याक गर्नुहोस्',
    'feature.analytics.title': 'उन्नत विश्लेषण',
    'feature.analytics.desc': 'डाटा-संचालित व्यापार निर्णयहरू गर्न व्यापक रिपोर्ट र अन्तर्दृष्टि',
    'feature.multirole.title': 'बहु-भूमिका प्रणाली',
    'feature.multirole.desc': 'सुपर एडमिन, एडमिन, म्यानेजर, क्यासियर, र फाइनान्स भूमिकाहरू अनुकूलन अनुमतिहरूसहित',
    'feature.billing.title': 'बिलिङ र अर्डर',
    'feature.billing.desc': 'NPR मुद्रा, eSewa, र FonePay एकीकरणको साथ पूर्ण अर्डर व्यवस्थापन',
    'feature.supplier.title': 'आपूर्तिकर्ता व्यवस्थापन',
    'feature.supplier.desc': 'विक्रेताहरू व्यवस्थापन गर्नुहोस्, खरिद ट्र्याक गर्नुहोस्, र बहु-विक्रेता सञ्चालन ह्यान्डल गर्नुहोस्',
    'feature.secure.title': 'सुरक्षित र भरपर्दो',
    'feature.secure.desc': 'वास्तविक समय अनुमति सिङ्क र डाटा सुरक्षाको साथ बैंक-स्तर सुरक्षा',
    
    // Stats
    'stats.parts': 'पार्ट्स ट्र्याक गरिएको',
    'stats.roles': 'प्रयोगकर्ता भूमिका',
    'stats.languages': 'भाषाहरू',
    'stats.sync': 'वास्तविक समय सिङ्क',
    
    // How It Works
    'howitworks.badge': 'यसले कसरी काम गर्छ',
    'howitworks.title': '४ सरल चरणहरूमा सुरु गर्नुहोस्',
    'howitworks.subtitle': 'मिनेटमा आफ्नो अटो पार्ट्स सूची व्यवस्थापन सुरु गर्नुहोस्',
    'howitworks.step1.title': 'दर्ता र लगइन',
    'howitworks.step1.desc': 'आफ्नो खाता सिर्जना गर्नुहोस् वा अवस्थित प्रमाणहरूसँग लगइन गर्नुहोस्',
    'howitworks.step2.title': 'सूची सेटअप गर्नुहोस्',
    'howitworks.step2.desc': 'आफ्नो पार्ट्स, कोटी, र मूल्य निर्धारण जानकारी थप्नुहोस्',
    'howitworks.step3.title': 'सञ्चालन व्यवस्थापन',
    'howitworks.step3.desc': 'अर्डर ट्र्याक गर्नुहोस्, बिलिङ ह्यान्डल गर्नुहोस्, र आफ्नो टोली व्यवस्थापन गर्नुहोस्',
    'howitworks.step4.title': 'आफ्नो व्यापार बढाउनुहोस्',
    'howitworks.step4.desc': 'राम्रो निर्णयहरू गर्न विश्लेषण र अन्तर्दृष्टि प्रयोग गर्नुहोस्',
    
    // Testimonials
    'testimonials.badge': 'प्रशंसापत्र',
    'testimonials.title': 'हाम्रा प्रयोगकर्ताहरू के भन्छन्',
    'testimonials.subtitle': 'नेपालभरि व्यवसायहरूद्वारा विश्वसनीय',
    'testimonials.1.text': 'सर्भ स्पेयर्सले हामी कसरी आफ्नो पार्ट्स सूची व्यवस्थापन गर्छौं भन्ने रूपान्तरण गर्‍यो। बहु-भाषा समर्थन उत्कृष्ट छ!',
    'testimonials.1.name': 'राजेश कुमार',
    'testimonials.1.role': 'पसल मालिक, काठमाडौं',
    'testimonials.2.text': 'वास्तविक समय सिङ्क र बारकोड स्क्यानिङले हाम्रो सञ्चालन धेरै छिटो बनायो। अत्यधिक सिफारिस!',
    'testimonials.2.name': 'सीता शर्मा',
    'testimonials.2.role': 'सूची प्रबन्धक',
    'testimonials.3.text': 'अनुमति प्रणाली उत्तम छ। प्रत्येक कर्मचारी सदस्यसँग उनीहरूलाई आवश्यक पहुँच छ।',
    'testimonials.3.name': 'अनिल थापा',
    'testimonials.3.role': 'व्यापार मालिक',
    
    // CTA
    'cta.title': 'आफ्नो सूची रूपान्तरण गर्न तयार हुनुहुन्छ?',
    'cta.subtitle': 'सर्भ स्पेयर्स प्रयोग गरिरहेका सयौं व्यवसायहरूमा सामेल हुनुहोस्',
    
    // Footer
    'footer.description': 'बहु-भूमिका पहुँच, वास्तविक समय सिङ्क, र व्यापक सुविधाहरूको साथ दुई-पाङ्ग्रे र चार-पाङ्ग्रे सवारी साधनका लागि पूर्ण सूची व्यवस्थापन समाधान।',
    'footer.quicklinks': 'द्रुत लिङ्कहरू',
    'footer.plans': 'योजनाहरू',
    'footer.company': 'कम्पनी',
    'footer.support': 'समर्थन',
    'footer.contact': 'सम्पर्क',
    'footer.features': 'विशेषताहरू',
    'footer.howitworks': 'यसले कसरी काम गर्छ',
    'footer.reviews': 'समीक्षाहरू',
    'footer.about': 'हाम्रो बारेमा',
    'footer.blog': 'ब्लग',
    'footer.pricing': 'मूल्य निर्धारण',
    'footer.faq': 'बारम्बार सोधिने प्रश्नहरू',
    'footer.terms': 'नियम र सर्तहरू',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.contactus': 'हामीलाई सम्पर्क गर्नुहोस्',
    'footer.email': 'support@servespares.com',
    'footer.phone': '+९७७ १२३४५६७८९०',
    'footer.address': 'काठमाडौं, नेपाल',
    'footer.hours': '२४/७ समर्थन',
    'footer.copyright': 'सर्वाधिकार सुरक्षित।',
    'footer.secure': 'सुरक्षित',
    'footer.reliable': 'भरपर्दो',
    'footer.fast': 'छिटो',
    'footer.blog.title': 'हाम्रो ब्लग अन्वेषण गर्नुहोस्',
    'footer.blog.subtitle': 'तपाईंको व्यापार यात्रा उचाल्न अन्तर्दृष्टिपूर्ण लेख र सुझावहरू पत्ता लगाउनुहोस्।',
    'footer.blog.readmore': 'थप पढ्नुहोस्',
    'footer.app.title': 'एक टच मा जडान र व्यवस्थापन गर्नुहोस् !',
    'footer.app.subtitle': 'सूची ट्र्याक गर्नुहोस्, कार्यहरू सुव्यवस्थित गर्नुहोस्, सहज मोबाइल एप सुनिश्चित गर्नुहोस्। सम्पत्ति थप्नुहोस्, बिक्री व्यवस्थापन गर्नुहोस्, आफ्नो समग्र प्रदर्शन ट्र्याक गर्नुहोस्, र आफ्नो फोन वा ट्याब्लेटबाट सीधै सबै सम्पत्तिहरू पहुँच गर्नुहोस्।',
    'footer.app.tagline': 'तपाईं र तपाईंको अटो पार्ट्स व्यवसायको लागि एक उत्तम साझेदार',
    'footer.app.cta': 'हामीसँग सुरु गर्नुहोस्',
    'footer.follow': 'सामाजिक सञ्जालमा हामीलाई फलो गर्नुहोस्',
    
    // About Page
    'about.title': 'सर्भ स्पेयर्स बारे',
    'about.subtitle': 'नेपाल र बाहिर दुई-पाङ्ग्रे र चार-पाङ्ग्रे अटो पार्ट्स सूची व्यवस्थापनमा क्रान्ति गर्दै।',
    'about.mission.title': 'हाम्रो मिशन',
    'about.mission.desc': 'अटो पार्ट्स व्यवसायहरूलाई व्यवस्थापन गर्ने शक्तिशाली तकनीकालाई उपलब्ध गराउन तपाईंको सञ्चालनहरूलाई सरल गर्न, ग्राहक सेवालाई बढाउन र निर्धारणयोग्य विकास गर्न।',
    'about.vision.title': 'हाम्रो दृष्टिकोण',
    'about.vision.desc': 'अटो पार्ट्स व्यवसायहरूको लागि लीडिङ व्यवस्थापन समाधान बन्न तपाईंको सम्पत्तिहरूको समग्र प्रदर्शन ट्र्याक गर्न दक्षिण एशियाको सबै आकारका दुकानहरूमा उपलब्ध गराउन।',
    'about.story.title': 'हाम्रो कथा',
    'about.story.p1': '२०२३मा स्थापना गरिएको सर्भ स्पेयर्सले नेपालमा अटो पार्ट्स दुकानमालिकाहरूलाई अपडेट नभएको व्यवस्थापन प्रणालीहरूसँग तालुका गर्दै थिएको अनुबन्धबाट जन्म लिन्छ। त्यसको बढाउन तयार छन्।',
    'about.story.p2': 'हाम्रो स्थापनकारहरू, ऑटोमोबाइल उद्योगमा अनुभवी उद्योगीहरू, दुई-पाङ्ग्रे र चार-पाङ्ग्रे पार्ट्स व्यवस्थापनको लागि विशेष रूपमा डिजाइन गरिएको प्लेटफार्म बनाउन एक टीम राम्रो विकासकारीहरू र उद्योग विशेषज्ञहरूलाई समेत गरेका थिए। हामीले विशेष चुनौतिहरूलाई समझेका थिए - अल्पकानीय एसक्यूकाहरूको प्रबंधन र बहु-विक्रेता र स्थानहरूको प्रबंधन जस्तै।',
    'about.story.p3': 'आज, हामी नेपालभरि व्यवसायहरूलाई सेवा गर्दै र दक्षिण एशियामा विस्तार गर्दै छौं। हाम्रो प्लेटफार्म बहु-भूमिका पहुँच, वास्तविक समय सिङ्क, बारकोड स्क्यानिङ र व्यापक अर्डर व्यवस्थापन समर्थन गर्दै छ - सबै नेपाली बाजारको लागि नेपाली रुपयामा, लोकाल भुगतान तरिकाहरू जस्तै eSewa र FonePay, र बहु-भाषा समर्थन जस्तै निर्मित छ।',
    'about.values.title': 'हाम्रो मुख्य मूल्यहरू',
    'about.values.subtitle': 'यी सिद्धान्तहरू हाम्रो सबै कुराहरूलाई निर्देशन दिन्छ र तपाईंसँग हाम्रो समर्थनको प्रतिबिम्ब बनाउन छन्।',
    'about.values.innovation': 'नवाचारण',
    'about.values.innovation.desc': 'अटो पार्ट्स प्रबंधनको लागि निरन्तर विकास गर्दै र सक्तिशाली तकनीकालाई प्रयोग गर्दै छ।',
    'about.values.customer': 'ग्राहक पहिला',
    'about.values.customer.desc': 'तपाईंको सफलता हाम्रो सफलता हो। हामी सुन्दैन्छ, परिवर्तन गर्दैन्छ र प्रदान गर्दैन्छ।',
    'about.values.reliability': 'निश्चितता',
    'about.values.reliability.desc': 'बैंक-स्तर सुरक्षाको साथ ९९.९% अपटाइम जुन तपाईंलाई निश्चित गर्दै छ।',
    'about.values.local': 'लोकाल ध्येय',
    'about.values.local.desc': 'नेपाली रुपयामा, eSewa, FonePay, र लोकाल भाषाको समर्थनको साथ नेपालको लागि निर्मित छ।',
    'about.values.scalability': 'स्केलेबिलिटी',
    'about.values.scalability.desc': 'एक दुकानबाट बहु-शाखाको सञ्चालन भन्दा बढी, हामी तपाईंसँग विस्तार गर्दै रहेका छौं।',
    'about.values.efficiency': 'कार्यक्षम���ा',
    'about.values.efficiency.desc': 'समय बचाउन र लाभ बढाउन व्यवस्थित कार्यक्रमहरू।',
    'about.stats.users': 'सक्रिय प्रयोगकर्ता',
    'about.stats.parts': 'पार्ट्स ट्र्याक गरिएको',
    'about.stats.uptime': 'अपटाइम एसएलए',
    'about.stats.support': 'समर्थन',
    
    // Features Page
    'features.title': 'शक्तिशाली विशेषताहरू',
    'features.subtitle': 'तपाईंको अटो पार्ट्स सूची व्यवस्थापनलाई प्रभावी र लाभाधिकारी रूपमा प्रबंधन गर्न तपाईंलाई चाहिने सबै कुरा।',
    'features.core.badge': 'मूल विशेषताहरू',
    'features.core.title': 'तपाईंलाई चाहिने सबै कुरा',
    'features.core.subtitle': 'अटो पार्ट्स सूची व्यवस्थापनको लागि विशेष रूपमा डिजाइन गरिएका व्यापक उपकरणहरू।',
    'features.inventory.title': 'सूची व्यवस्थापन',
    'features.inventory.desc': 'दुई-पाङ्ग्रे र चार-पाङ्ग्रे पार्ट्सको पूर्ण पार्ट्स ट्र्याकिङ र वास्तविक समय स्टॉक अपडेटहरूसँग।',
    'features.inventory.f1': 'बहु-कोटी समर्थन',
    'features.inventory.f2': 'स्टॉक स्तर ट्र्याकिङ',
    'features.inventory.f3': 'कम स्टॉक अलर्टहरू',
    'features.inventory.f4': 'पार्ट नम्बर खोज्नुहोस्',
    'features.barcode.title': 'बारकोड स्क्यानिङ',
    'features.barcode.desc': 'तेज सूची अपडेट र अर्डर प्रसंस्करणको लागि बारकोड स्क्यानिङ प्रणाली।',
    'features.barcode.f1': 'बलक आयात/निर्यात',
    'features.barcode.f2': 'स्क्यान गर्नुहोस् र खोज्नुहोस्',
    'features.barcode.f3': 'तेज बिलिङ',
    'features.barcode.f4': 'सूची अपडेटहरू',
    'features.orders.title': 'अर्डर व्यवस्थापन',
    'features.orders.desc': 'ग्राहक र आपूर्तिकर्ताको पूर्ण प्रबंधनको साथ ७ श्तरीय अर्डर जीवनचक्र।',
    'features.orders.f1': 'ड्राफ्ट र भेटिएको',
    'features.orders.f2': 'ग्राहक अर्डरहरू',
    'features.orders.f3': 'आपूर्तिकर्ता अर्डरहरू',
    'features.orders.f4': 'अर्डर इतिहास',
    'features.billing.title': 'बिलिङ प्रणाली',
    'features.billing.desc': 'NPR मुद्रा र लोकाल भुगतान एकीकरणहरूसँग पूर्ण बिलिङ।',
    'features.billing.f1': 'eSewa एकीकरण',
    'features.billing.f2': 'FonePay समर्थन',
    'features.billing.f3': 'इन्वाइस उत्पन्न गर्नुहोस्',
    'features.billing.f4': 'भुगतान ट्र्याकिङ',
    'features.roles.title': 'बहु-भूमिका पहुँच',
    'features.roles.desc': 'हारियराखी अनुमतिहरू र वास्तविक समय सिङ्कको साथ ५ प्रयोगकर्ता भूमिकाहरू।',
    'features.roles.f1': 'सुपर एडमिन',
    'features.roles.f2': 'एडमिन',
    'features.roles.f3': 'सूची प्रबन्धक',
    'features.roles.f4': 'क्यासियर',
    'features.roles.f5': 'फाइनान्स',
    'features.analytics.title': 'विश्लेषण र रिपोर्टहरू',
    'features.analytics.desc': 'डाटा-संचालित व्यापार निर्णयहरू गर्न व्यापक ब्यापार अन्तर्दृष्टिहरू र उपकरणहरू।',
    'features.analytics.f1': 'बिक्री रिपोर्टहरू',
    'features.analytics.f2': 'सूची विश्लेषण',
    'features.analytics.f3': 'लाभ ट्र्याकिङ',
    'features.analytics.f4': 'प्रदर्शन मेट्रिकहरू',
    'features.categories.title': 'विशेषताहरूको श्रेणीहरू',
    'features.categories.subtitle': 'तपाईंको अटो पार्ट्स व्यवसायको हर अनुभागको लागि व्यवस्थित उपकरणहरू।',
    'features.cat1.title': 'सूची नियंत्रण',
    'features.cat1.f1': 'उत्पादन श्रेणीहरू',
    'features.cat1.f2': 'SKU प्रबंधन',
    'features.cat1.f3': 'स्टॉक ट्र्याकिङ',
    'features.cat1.f4': 'वार्डरोम प्रबंधन',
    'features.cat1.f5': 'पुन:आर्डर स्तरहरू',
    'features.cat1.f6': 'सूची रिपोर्टहरू',
    'features.cat2.title': 'ग्राहक र आपूर्तिकर्ता',
    'features.cat2.f1': 'पार्टी प्रबंधन',
    'features.cat2.f2': 'ग्राहक प्रोफाइलहरू',
    'features.cat2.f3': 'आपूर्तिकर्ता डाटाबेस',
    'features.cat2.f4': 'क्रेडिट प्रबंधन',
    'features.cat2.f5': 'खरिद इतिहास',
    'features.cat2.f6': 'आपूर्तिकर्ता प्रदर्शन',
    'features.cat3.title': 'शाखा सञ्चालनहरू',
    'features.cat3.f1': 'बहु-शाखा समर्थन',
    'features.cat3.f2': 'शाखा विश्लेषण',
    'features.cat3.f3': 'स्टॉक ट्रान्सफर',
    'features.cat3.f4': 'शाखा अनुमतिहरू',
    'features.cat3.f5': 'स्थान ट्र्याकिङ',
    'features.cat3.f6': 'केन्द्रीय नियंत्रण',
    'features.cat4.title': 'बहु-भाषा',
    'features.cat4.f1': 'अंग्रेजी',
    'features.cat4.f2': 'नेपाली',
    'features.cat4.f3': 'हिंदी',
    'features.cat4.f4': 'स्पेनिश',
    'features.cat4.f5': 'फ्रान्सीसी',
    'features.cat4.f6': 'जर्मन',
    'features.cat4.f7': 'चीनी',
    'features.cat4.f8': 'जापानी',
    'features.technical.badge': 'तकनीकी उत्कृष्टता',
    'features.technical.title': 'उन्नत तकनीका',
    'features.technical.subtitle': 'माध्यमिक तकनीकालाई प्रयोग गरिएको अधिकतम प्रदर्शन र निश्चितताको लागि।',
    'features.tech1.title': 'वास्तविक समय सिङ्क',
    'features.tech1.desc': 'सबै प्रयोगकर्ताहरूमा अनुमति र भाषा अपडेटहरू',
    'features.tech2.title': '८ भाषाहरू',
    'features.tech2.desc': 'फ्लैग-आधारित UIको साथ पूर्ण बहु-भाषा समर्थन',
    'features.tech3.title': 'पहुँच नियंत्रण',
    'features.tech3.desc': 'सुपरएडमिन संरक्षणको साथ हारियराखी अनुमति प्रणाली',
    'features.tech4.title': 'उत्तरदायी डिजाइन',
    'features.tech4.desc': 'डेस्कटॉप, टेबलेट, र मोबाइल डिवाइसहरूमा पूर्ण रूपमा काम गर्दै छ',
    'features.tech5.title': 'कस्तुम अलर्टहरू',
    'features.tech5.desc': 'डिफोल्ट अलर्टहरूको साथ सुंदर ब्रान्ड डायलॉग प्रणाली',
    'features.tech6.title': 'कस्तुमाइजेबल',
    'features.tech6.desc': 'तपाईंको विशिष्ट व्यवसायी आवश्यकताहरूको लागि प्रणालीलाई टेलर कर्नुहोस्',
    'features.security.title': 'कार्यालय ग्रेड सुरक्षा',
    'features.security.subtitle': 'तपाईंको व्यवसाय डाटा र ग्राहक जानकारी उच्च सुरक्षा मानकहरूसँग संरक्षित छ।',
    'features.security1.title': 'बैंक-स्तर एन्क्रिप्शन',
    'features.security1.desc': 'भाण्डारण तकनीकी मानकहरूसँग सबै डाटा एन्क्रिप्शन',
    'features.security2.title': '९९.९% अपटाइम',
    'features.security2.desc': 'हर दिन आपनाइएको निश्चित सेवा',
    'features.security3.title': 'स्थानिय र सुरक्षित',
    'features.security3.desc': 'स्थानिय संरक्षणको साथ सुरक्षित रखिएको डाटा',
    'features.security4.title': 'वास्तविक समय बैकअप',
    'features.security4.desc': 'तपाईंको डाटा निरन्तर बैकअप र संरक्षित गरिएको छ',
    
    // Pricing Page
    'pricing.title': 'सरल, पारदर्शी मूल्य निर्धारण',
    'pricing.subtitle': 'आफ्नो अटो पार्ट्स व्यवसायको लागि उत्तम योजना छान्नुहोस्। कुनै लुकेको शुल्क छैन, जुनसुकै बेला रद्द गर्नुहोस्।',
    'pricing.monthly': 'मासिक',
    'pricing.yearly': 'वार्षिक',
    'pricing.save': '२०% बचत गर्नुहोस्',
    'pricing.popular': 'सबैभन्दा लोकप्रिय',
    'pricing.getstarted': 'सुरु गर्नुहोस्',
    'pricing.plan.starter': 'स्टार्टर',
    'pricing.plan.professional': 'प्रोफेशनल',
    'pricing.plan.enterprise': 'इन्टरप्राइज',
    'pricing.starter.desc': 'सानो अटो पार्ट्स पसलहरूको लागि उत्तम जो भर्खर सुरु गर्दैछन्',
    'pricing.professional.desc': 'बढ्दो व्यवसायहरूको लागि जसलाई थप शक्ति चाहिन्छ',
    'pricing.enterprise.desc': 'ठूला सञ्चालनहरूको लागि अनुकूलन आवश्यकताहरू सहित',
    'pricing.month': 'महिना',
    'pricing.year': 'वर्ष',
    'pricing.save.yearly': 'NPR बचत गर्नुहोस्',
    'pricing.peryear': '/वर्ष',
    'pricing.starter.f1': '१,००० सम्म पार्ट्स',
    'pricing.starter.f2': 'एकल स्थान',
    'pricing.starter.f3': 'आधारभूत सूची ट्र्याकिङ',
    'pricing.starter.f4': 'अर्डर व्यवस्थापन',
    'pricing.starter.f5': 'इमेल समर्थन',
    'pricing.starter.f6': '२ प्रयोगकर्ता खाताहरू',
    'pricing.starter.f7': 'बारकोड स्क्यानिङ',
    'pricing.starter.f8': 'बहु-शाखा',
    'pricing.starter.f9': 'उन्नत विश्लेषण',
    'pricing.professional.f1': '१०,००० सम्म पार्ट्स',
    'pricing.professional.f2': '३ सम्म स्थानहरू',
    'pricing.professional.f3': 'उन्नत सूची',
    'pricing.professional.f4': 'अर्डर व्यवस्थापन',
    'pricing.professional.f5': 'प्राथमिकता समर्थन',
    'pricing.professional.f6': '५ प्रयोगकर्ता खाताहरू',
    'pricing.professional.f7': 'बारकोड स्क्यानिङ',
    'pricing.professional.f8': 'विश्लेषण र रिपोर्ट',
    'pricing.professional.f9': 'बहु-भाषा',
    'pricing.enterprise.f1': 'असीमित पार्ट्स',
    'pricing.enterprise.f2': 'असीमित स्थानहरू',
    'pricing.enterprise.f3': 'पूर्ण सूची सुइट',
    'pricing.enterprise.f4': 'उन्नत अर्डर प्रणाली',
    'pricing.enterprise.f5': '२४/७ फोन समर्थन',
    'pricing.enterprise.f6': 'असीमित प्रयोगकर्ताहरू',
    'pricing.enterprise.f7': 'बारकोड स्क्यानिङ',
    'pricing.enterprise.f8': 'अनुकूलन विश्लेषण',
    'pricing.enterprise.f9': 'API पहुँच',
    'pricing.enterprise.f10': 'समर्पित खाता प्रबन्धक',
    'pricing.enterprise.f11': 'अनुकूलन प्रशिक्षण',
    'pricing.faq.title': 'बारम्बार सोधिने प्रश्नहरू',
    'pricing.faq.subtitle': 'हाम्रो मूल्य निर्धारणको बारेमा तपाईंले जान्न आवश्यक सबै कुरा',
    'pricing.faq.q1': 'के म पछि मेरो योजना परिवर्तन गर्न सक्छु?',
    'pricing.faq.a1': 'हो! तपाईं जुनसुकै बेला आफ्नो योजना अपग्रेड वा डाउनग्रेड गर्न सक्नुहुन्छ। परिवर्तनहरू तुरुन्तै प्रभावकारी हुन्छन्।',
    'pricing.faq.q2': 'तपाईं कुन भुक्तानी विधिहरू स्वीकार गर्नुहुन्छ?',
    'pricing.faq.a2': 'हामी eSewa, FonePay, क्रेडिट/डेबिट कार्ड, र बैंक स्थानान्तरण सहित सबै प्रमुख भुक्तानी विधिहरू स्वीकार गर्दछौं।',
    'pricing.faq.q3': 'के त्यहाँ नि:शुल्क परीक्षण छ?',
    'pricing.faq.a3': 'हो! हामी सबै योजनाहरूमा १४-दिनको नि:शुल्क परीक्षण प्रदान गर्दछौं। सुरु गर्न कुनै क्रेडिट कार्ड आवश्यक छैन।',
    'pricing.faq.q4': 'के म जुनसुकै बेला रद्द गर्न सक्छु?',
    'pricing.faq.a4': 'निश्चित रूपमा। तपाईं जुनसुकै बेला आफ्नो सदस्यता रद्द गर्न सक्नुहुन्छ। कुनै प्रश्न सोधिएको छैन, कुनै जरिवाना छैन।',
    'pricing.faq.q5': 'के तपाईं वार्षिक बिलिङको लागि छुट प्रदान गर्नुहुन्छ?',
    'pricing.faq.a5': 'हो! वार्षिक बिलिङ छनौट गर्दा २०% बचत गर्नुहोस्। त्यो २+ महिना नि:शुल्क पाउनु जस्तै हो!',
    'pricing.faq.q6': 'के प्रशिक्षण समावेश छ?',
    'pricing.faq.a6': 'सबै योजनाहरूमा भिडियो ट्युटोरियल र दस्तावेज समावेश छ। इन्टरप्राइज योजनाहरूमा अनुकूलन प्रशिक्षण सत्रहरू समावेश छन्।',
    'pricing.cta.title': 'सुरु गर्न तयार हुनुहुन्छ?',
    'pricing.cta.subtitle': 'सर्भ स्पेयर्स प्रयोग गरिरहेका सयौं अटो पार्ट्स व्यवसायहरूमा सामेल हुनुहोस्',
    'pricing.cta.button': 'नि:शुल्क परीक्षण सुरु गर्नुहोस्',
    
    // Contact Page
    'contact.title': 'सम्पर्कमा रहनुहोस्',
    'contact.subtitle': 'सर्भ स्पेयर्स बारे प्रश्नहरू छन्? हामी तपाईंबाट सुन्न चाहन्छौं। हामीलाई सन्देश पठाउनुहोस् र हामी सकेसम्म चाँडो प्रतिक्रिया दिनेछौं।',
    'contact.form.title': 'हामीलाई सन्देश पठाउनुहोस्',
    'contact.form.subtitle': 'तलको फारम भर्नुहोस् र हाम्रो टोलीले तपाईंलाई चाँडै सम्पर्क गर्नेछ।',
    'contact.name': 'पूरा नाम',
    'contact.name.placeholder': 'राम बहादुर',
    'contact.email': 'इमेल ठेगाना',
    'contact.email.placeholder': 'ram@example.com',
    'contact.phone': 'फोन नम्बर',
    'contact.phone.placeholder': '+९७७ ९८७६५४३२१०',
    'contact.company': 'पसल/कम्पनीको नाम',
    'contact.company.placeholder': 'ABC अटो पार्ट्स',
    'contact.message': 'सन्देश',
    'contact.message.placeholder': 'तपाईंको अटो पार्ट्स व्यवसाय र हामी कसरी मद्दत गर्न सक्छौं भन्ने बारे बताउनुहोस्...',
    'contact.send': 'सन्देश पठाउनुहोस्',
    'contact.success': '✓ धन्यवाद! हामी २४ घण्टा भित्र तपाईंलाई सम्पर्क गर्नेछौं।',
    'contact.info.title': 'सम्पर्क जानकारी',
    'contact.info.email': 'हामीलाई इमेल गर्नुहोस्',
    'contact.info.email.value': 'support@servespares.com',
    'contact.info.email.sub': 'हामी २४ घण्टा भित्र जवाफ दिन्छौं',
    'contact.info.phone': 'हामीलाई फोन गर्नुहोस्',
    'contact.info.phone.value': '+९७७ १२३४५६७८९०',
    'contact.info.phone.sub': 'सोमबार-शनिबार, बिहान ९-साँझ ६ बजे',
    'contact.info.visit': 'हामीलाई भेट्नुहोस्',
    'contact.info.visit.value': 'थमेल, काठमाडौं',
    'contact.info.visit.sub': 'नेपाल',
    'contact.map.title': 'काठमाडौं, नेपाल',
    'contact.map.subtitle': 'देशभरि अटो पार्ट्स पसलहरूलाई सेवा दिँदै',
    'contact.locations.title': 'नेपालमा हाम्रो उपस्थिति',
    'contact.locations.subtitle': 'देशभरि अटो पार्ट्स व्यवसायहरूलाई समर्थन गर्दै।',
    'contact.location.kathmandu': 'काठमाडौं',
    'contact.location.kathmandu.region': 'केन्द्रीय नेपाल',
    'contact.location.kathmandu.address': 'थमेल, काठमाडौं ४४६००',
    'contact.location.pokhara': 'पोखरा',
    'contact.location.pokhara.region': 'पश्चिमी नेपाल',
    'contact.location.pokhara.address': 'लेकसाइड, पोखरा',
    'contact.location.biratnagar': 'विराटनगर',
    'contact.location.biratnagar.region': 'पूर्वी नेपाल',
    'contact.location.biratnagar.address': 'मुख्य सडक, विराटनगर',
    'contact.location.bharatpur': 'भरतपुर',
    'contact.location.bharatpur.region': 'केन्द्रीय नेपाल',
    'contact.location.bharatpur.address': 'पुलचोक, भरतपुर',
    'contact.support.title': 'मद्दत चाहिन्छ?',
    'contact.support.subtitle': 'तपाईंलाई आवश्यक पर्दा सहयोग प्राप्त गर्ने धेरै तरिकाहरू।',
    'contact.support.chat': 'लाइभ च्याट',
    'contact.support.chat.desc': 'कार्यालय समयमा हाम्रो समर्थन टोलीसँग वास्तविक समयमा कुराकानी गर्नुहोस्',
    'contact.support.chat.action': 'च्याट सुरु गर्नुहोस्',
    'contact.support.email': 'इमेल समर्थन',
    'contact.support.email.desc': 'हामीलाई इमेल पठाउनुहोस् र २४ घण्टा भित्र जवाफ पाउनुहोस्',
    'contact.support.email.action': 'इमेल पठाउनुहोस्',
    'contact.support.help': 'सहायता केन्द्र',
    'contact.support.help.desc': 'हाम्रो व्यापक दस्तावेज र भिडियो ट्युटोरियलहरू ब्राउज गर्नुहोस्',
    'contact.support.help.action': 'सहायता केन्द्र भ्रमण गर्नुहोस्',
    'contact.support.forum': 'समुदाय फोरम',
    'contact.support.forum.desc': 'सर्भ स्पेयर्स प्रयोग गर्ने अन्य अटो पार्ट्स पसल मालिकहरूसँग जडान गर्नुहोस्',
    'contact.support.forum.action': 'फोरममा सामेल हुनुहोस्',
  }
};

export const LandingLanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<LandingLanguage>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LandingLanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LandingLanguageContext.Provider>
  );
};

export const useLandingLanguage = () => {
  const context = useContext(LandingLanguageContext);
  if (!context) {
    throw new Error('useLandingLanguage must be used within LandingLanguageProvider');
  }
  return context;
};