import { User, InventoryItem, Transaction, Workspace, Party } from '../types';

export const MOCK_USERS: User[] = [
  {
    id: '1',
    email: 'superadmin@autoparts.com',
    password: 'super123',
    role: 'super_admin',
    name: 'Super Administrator',
    phone: '+977 9801234567',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    email: 'admin@autoparts.com',
    password: 'admin123',
    role: 'admin',
    name: 'Rajesh Sharma',
    phone: '+977 9811234567',
    workspaceId: 'ws1',
    createdAt: '2024-01-15T00:00:00Z',
    createdBy: '1',
  },
  {
    id: '3',
    email: 'manager@autoparts.com',
    password: 'manager123',
    role: 'inventory_manager',
    name: 'Sita Thapa',
    phone: '+977 9821234567',
    workspaceId: 'ws1',
    createdAt: '2024-01-20T00:00:00Z',
    createdBy: '2',
  },
  {
    id: '4',
    email: 'cashier@autoparts.com',
    password: 'cashier123',
    role: 'cashier',
    name: 'Bikash Gurung',
    phone: '+977 9831234567',
    workspaceId: 'ws1',
    createdAt: '2024-01-25T00:00:00Z',
    createdBy: '2',
  },
  {
    id: '5',
    email: 'finance@autoparts.com',
    password: 'finance123',
    role: 'finance',
    name: 'Anjali Rai',
    phone: '+977 9841234567',
    workspaceId: 'ws1',
    createdAt: '2024-01-30T00:00:00Z',
    createdBy: '2',
  },
];

export const MOCK_WORKSPACES: Workspace[] = [
  {
    id: 'ws1',
    name: 'Main Branch',
    adminId: '2',
    createdAt: '2024-01-15T00:00:00Z',
  },
];

export const MOCK_PARTIES: Party[] = [
  {
    id: 'party1',
    name: 'Kathmandu Auto Parts Pvt. Ltd.',
    type: 'distributor',
    contactPerson: 'Ramesh Shrestha',
    phone: '+977 9851111111',
    email: 'ramesh@ktmauto.com.np',
    address: 'Kalimati Road, Ward No. 14',
    city: 'Kathmandu',
    state: 'Bagmati',
    pincode: '44600',
    gstNumber: '',
    panNumber: '123456789',
    paymentTerms: 'credit_30',
    creditLimit: 500000,
    openingBalance: 0,
    currentBalance: 125000,
    workspaceId: 'ws1',
    createdAt: '2024-01-16T00:00:00Z',
    createdBy: '2',
    isActive: true,
  },
  {
    id: 'party2',
    name: 'Himalayan Motors Supply',
    type: 'wholesaler',
    contactPerson: 'Suresh Tamang',
    phone: '+977 9802222222',
    email: 'suresh@himalayan.com.np',
    address: 'New Road, Sundhara',
    city: 'Kathmandu',
    state: 'Bagmati',
    pincode: '44600',
    gstNumber: '',
    panNumber: '234567890',
    paymentTerms: 'credit_45',
    creditLimit: 750000,
    openingBalance: 0,
    currentBalance: 245000,
    workspaceId: 'ws1',
    createdAt: '2024-01-16T00:00:00Z',
    createdBy: '2',
    isActive: true,
  },
  {
    id: 'party3',
    name: 'Pokhara Spare Parts Center',
    type: 'supplier',
    contactPerson: 'Krishna Gurung',
    phone: '+977 9813333333',
    email: 'krishna@pokharaparts.com',
    address: 'Lakeside Road, Ward No. 6',
    city: 'Pokhara',
    state: 'Gandaki',
    pincode: '33700',
    gstNumber: '',
    panNumber: '345678901',
    paymentTerms: 'credit_30',
    creditLimit: 300000,
    openingBalance: 0,
    currentBalance: 89000,
    workspaceId: 'ws1',
    createdAt: '2024-01-17T00:00:00Z',
    createdBy: '2',
    isActive: true,
  },
  {
    id: 'party4',
    name: 'Biratnagar Auto Traders',
    type: 'distributor',
    contactPerson: 'Suman Rai',
    phone: '+977 9824444444',
    email: 'suman@biratnagar.com.np',
    address: 'Traffic Chowk, Main Road',
    city: 'Biratnagar',
    state: 'Koshi',
    pincode: '56600',
    gstNumber: '',
    panNumber: '456789012',
    paymentTerms: 'credit_15',
    creditLimit: 400000,
    openingBalance: 0,
    currentBalance: 167000,
    workspaceId: 'ws1',
    createdAt: '2024-01-18T00:00:00Z',
    createdBy: '2',
    isActive: true,
  },
  {
    id: 'party5',
    name: 'Lalitpur Vehicle Parts',
    type: 'supplier',
    contactPerson: 'Binod Shakya',
    phone: '+977 9835555555',
    email: 'binod@lalitpurparts.com',
    address: 'Mangal Bazaar, Patan',
    city: 'Lalitpur',
    state: 'Bagmati',
    pincode: '44700',
    gstNumber: '',
    panNumber: '567890123',
    paymentTerms: 'credit_7',
    creditLimit: 200000,
    openingBalance: 0,
    currentBalance: 56000,
    workspaceId: 'ws1',
    createdAt: '2024-01-19T00:00:00Z',
    createdBy: '2',
    isActive: true,
  },
  {
    id: 'party6',
    name: 'Bhaktapur Auto Wholesale',
    type: 'wholesaler',
    contactPerson: 'Manoj Bajracharya',
    phone: '+977 9846666666',
    email: 'manoj@bhaktapurauto.com',
    address: 'Durbar Square Road',
    city: 'Bhaktapur',
    state: 'Bagmati',
    pincode: '44800',
    gstNumber: '',
    panNumber: '678901234',
    paymentTerms: 'cash',
    creditLimit: 0,
    openingBalance: 0,
    currentBalance: 0,
    workspaceId: 'ws1',
    createdAt: '2024-01-20T00:00:00Z',
    createdBy: '2',
    isActive: true,
  },
  {
    id: 'party7',
    name: 'Thamel Auto Suppliers',
    type: 'supplier',
    contactPerson: 'Prakash Thapa',
    phone: '+977 9857777777',
    email: 'prakash@thamelauto.com',
    address: 'Thamel Marg, Ward No. 26',
    city: 'Kathmandu',
    state: 'Bagmati',
    pincode: '44600',
    gstNumber: '',
    panNumber: '789012345',
    paymentTerms: 'credit_15',
    creditLimit: 150000,
    openingBalance: 0,
    currentBalance: 34000,
    workspaceId: 'ws1',
    createdAt: '2024-01-21T00:00:00Z',
    createdBy: '2',
    isActive: true,
  },
];

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: 'inv1',
    name: 'Engine Oil - Castrol 20W-50',
    category: 'branded',
    vehicleType: 'four_wheeler',
    quantity: 45,
    minStockLevel: 10,
    price: 850,
    mrp: 950,
    partyId: 'party1',
    partNumber: 'CTL-20W50-1L',
    hsnCode: '27101990',
    location: 'Shelf A-12',
    workspaceId: 'ws1',
    createdAt: '2024-11-20T10:30:00Z',
  },
  {
    id: 'inv2',
    name: 'Brake Pads - Local',
    category: 'local',
    vehicleType: 'two_wheeler',
    quantity: 120,
    minStockLevel: 20,
    price: 350,
    mrp: 450,
    partyId: 'party7',
    partNumber: 'BP-2W-STD',
    hsnCode: '87083010',
    location: 'Shelf B-05',
    workspaceId: 'ws1',
    createdAt: '2024-11-22T14:20:00Z',
  },
  {
    id: 'inv3',
    name: 'Air Filter - Bosch',
    category: 'branded',
    vehicleType: 'four_wheeler',
    quantity: 8,
    minStockLevel: 15,
    price: 1200,
    mrp: 1400,
    partyId: 'party2',
    partNumber: 'BSH-AF-4W-001',
    hsnCode: '84213990',
    location: 'Shelf A-08',
    workspaceId: 'ws1',
    createdAt: '2024-11-23T09:15:00Z',
  },
  {
    id: 'inv4',
    name: 'Spark Plug - NGK',
    category: 'branded',
    vehicleType: 'two_wheeler',
    quantity: 200,
    minStockLevel: 50,
    price: 180,
    mrp: 220,
    partyId: 'party3',
    partNumber: 'NGK-SP-2W-CR7',
    hsnCode: '85113090',
    location: 'Shelf C-14',
    workspaceId: 'ws1',
    createdAt: '2024-11-24T11:00:00Z',
  },
  {
    id: 'inv5',
    name: 'Battery - Exide',
    category: 'branded',
    vehicleType: 'four_wheeler',
    quantity: 12,
    minStockLevel: 5,
    price: 4500,
    mrp: 5200,
    partyId: 'party4',
    partNumber: 'EXD-BAT-4W-50AH',
    hsnCode: '85071000',
    location: 'Warehouse 2',
    workspaceId: 'ws1',
    createdAt: '2024-11-24T08:30:00Z',
  },
  {
    id: 'inv6',
    name: 'Chain Sprocket - Local',
    category: 'local',
    vehicleType: 'two_wheeler',
    quantity: 35,
    minStockLevel: 10,
    price: 650,
    mrp: 800,
    partyId: 'party7',
    partNumber: 'CS-2W-STD-001',
    hsnCode: '87149100',
    location: 'Shelf B-18',
    workspaceId: 'ws1',
    createdAt: '2024-11-23T16:45:00Z',
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn1',
    items: [
      { itemId: 'inv1', itemName: 'Engine Oil - Castrol 20W-50', quantity: 2, price: 850 },
      { itemId: 'inv4', itemName: 'Spark Plug - NGK', quantity: 4, price: 180 },
    ],
    total: 2420,
    customerName: 'Rajesh Kumar',
    customerPhone: '+91 98765 43210',
    paymentMethod: 'upi',
    processedBy: '3',
    workspaceId: 'ws1',
    createdAt: '2024-11-24T10:30:00Z',
  },
  {
    id: 'txn2',
    items: [
      { itemId: 'inv5', itemName: 'Battery - Exide', quantity: 1, price: 4500 },
    ],
    total: 4500,
    customerName: 'Priya Sharma',
    customerPhone: '+91 87654 32109',
    paymentMethod: 'card',
    processedBy: '3',
    workspaceId: 'ws1',
    createdAt: '2024-11-24T11:15:00Z',
  },
];

// Helper functions for localStorage
export const saveToStorage = (key: string, data: any) => {
  localStorage.setItem(key, JSON.stringify(data));
};

export const getFromStorage = (key: string, defaultValue: any = null) => {
  const stored = localStorage.getItem(key);
  return stored ? JSON.parse(stored) : defaultValue;
};

export const initializeStorage = () => {
  if (!localStorage.getItem('users')) {
    saveToStorage('users', MOCK_USERS);
  }
  if (!localStorage.getItem('workspaces')) {
    saveToStorage('workspaces', MOCK_WORKSPACES);
  }
  if (!localStorage.getItem('parties')) {
    saveToStorage('parties', MOCK_PARTIES);
  }
  if (!localStorage.getItem('inventory')) {
    saveToStorage('inventory', MOCK_INVENTORY);
  }
  if (!localStorage.getItem('transactions')) {
    saveToStorage('transactions', MOCK_TRANSACTIONS);
  }
  if (!localStorage.getItem('customerOrders')) {
    saveToStorage('customerOrders', MOCK_CUSTOMER_ORDERS);
  }
};

// Get item sales statistics
export const getItemSalesStats = () => {
  const transactions: any[] = getFromStorage('transactions', []);
  const itemSales: Record<string, { name: string; quantity: number; revenue: number; purchases: number }> = {};
  
  transactions.forEach(txn => {
    txn.items.forEach((item: any) => {
      if (!itemSales[item.itemId]) {
        itemSales[item.itemId] = {
          name: item.itemName,
          quantity: 0,
          revenue: 0,
          purchases: 0,
        };
      }
      itemSales[item.itemId].quantity += item.quantity;
      itemSales[item.itemId].revenue += item.price * item.quantity;
      itemSales[item.itemId].purchases += 1;
    });
  });
  
  return Object.values(itemSales).sort((a, b) => b.quantity - a.quantity);
};

export const MOCK_CUSTOMER_ORDERS = [
  {
    id: 'order1',
    orderNumber: 'ORD-2024-001',
    customerName: 'Siddharth Shrestha',
    customerPhone: '+977 9841234567',
    customerAddress: 'Thamel, Ward No. 26',
    city: 'Kathmandu',
    state: 'Bagmati',
    pincode: '44600',
    items: [
      { itemId: 'inv1', itemName: 'Engine Oil - Castrol 20W-50', quantity: 10, price: 850, total: 8500 },
    ],
    subtotal: 8500,
    tax: 1105,
    discount: 0,
    total: 9605,
    status: 'pending',
    paymentMethod: 'cod',
    workspaceId: 'ws1',
    createdAt: '2024-03-16T11:30:00Z',
    createdBy: '2',
  },
  {
    id: 'order2',
    orderNumber: 'ORD-2024-002',
    customerName: 'Pratik Gurung',
    customerPhone: '+977 9851234568',
    customerAddress: 'Lazimpat Road, House No. 123',
    city: 'Kathmandu',
    state: 'Bagmati',
    pincode: '44600',
    items: [
      { itemId: 'inv4', itemName: 'Spark Plug - NGK', quantity: 2, price: 180, total: 360 },
    ],
    subtotal: 360,
    tax: 47,
    discount: 0,
    total: 407,
    status: 'pending',
    paymentMethod: 'paid',
    workspaceId: 'ws1',
    createdAt: '2024-03-16T11:30:00Z',
    createdBy: '2',
  },
  {
    id: 'order3',
    orderNumber: 'ORD-2024-003',
    customerName: 'Nabin Shrestha',
    customerPhone: '+977 9861234569',
    customerAddress: 'Patan Dhoka, Lalitpur',
    city: 'Lalitpur',
    state: 'Bagmati',
    pincode: '44700',
    items: [
      { itemId: 'inv2', itemName: 'Brake Pads - Local', quantity: 15, price: 350, total: 5250 },
    ],
    subtotal: 5250,
    tax: 683,
    discount: 0,
    total: 5933,
    status: 'pending',
    paymentMethod: 'cod',
    workspaceId: 'ws1',
    createdAt: '2024-03-16T11:30:00Z',
    createdBy: '2',
  },
  {
    id: 'order4',
    orderNumber: 'ORD-2024-004',
    customerName: 'Riden Paudel',
    customerPhone: '+977 9871234570',
    customerAddress: 'Boudha Stupa Area',
    city: 'Kathmandu',
    state: 'Bagmati',
    pincode: '44600',
    items: [
      { itemId: 'inv5', itemName: 'Battery - Exide', quantity: 20, price: 4500, total: 90000 },
    ],
    subtotal: 90000,
    tax: 11700,
    discount: 0,
    total: 101700,
    status: 'pending',
    paymentMethod: 'credit',
    workspaceId: 'ws1',
    createdAt: '2024-03-16T11:30:00Z',
    createdBy: '2',
  },
  {
    id: 'order5',
    orderNumber: 'ORD-2024-005',
    customerName: 'Bishal Paudel',
    customerPhone: '+977 9881234571',
    customerAddress: 'Koteshwor Chowk',
    city: 'Kathmandu',
    state: 'Bagmati',
    pincode: '44600',
    items: [
      { itemId: 'inv3', itemName: 'Air Filter - Bosch', quantity: 4, price: 1200, total: 4800 },
    ],
    subtotal: 4800,
    tax: 624,
    discount: 0,
    total: 5424,
    status: 'pending',
    paymentMethod: 'paid',
    workspaceId: 'ws1',
    createdAt: '2024-03-16T11:30:00Z',
    createdBy: '2',
  },
  {
    id: 'order6',
    orderNumber: 'ORD-2024-006',
    customerName: 'Ramesh Thapa',
    customerPhone: '+977 9891234572',
    customerAddress: 'Baneshwor, Main Road',
    city: 'Kathmandu',
    state: 'Bagmati',
    pincode: '44600',
    items: [
      { itemId: 'inv6', itemName: 'Chain Sprocket - Local', quantity: 5, price: 650, total: 3250 },
    ],
    subtotal: 3250,
    tax: 423,
    discount: 0,
    total: 3673,
    status: 'completed',
    paymentMethod: 'cod',
    workspaceId: 'ws1',
    createdAt: '2024-03-15T10:00:00Z',
    completedAt: '2024-03-15T16:00:00Z',
    createdBy: '2',
  },
  {
    id: 'order7',
    orderNumber: 'ORD-2024-007',
    customerName: 'Anjali Rai',
    customerPhone: '+977 9801234573',
    customerAddress: 'Bhaktapur Durbar Square',
    city: 'Bhaktapur',
    state: 'Bagmati',
    pincode: '44800',
    items: [
      { itemId: 'inv1', itemName: 'Engine Oil - Castrol 20W-50', quantity: 8, price: 850, total: 6800 },
    ],
    subtotal: 6800,
    tax: 884,
    discount: 0,
    total: 7684,
    status: 'completed',
    paymentMethod: 'paid',
    workspaceId: 'ws1',
    createdAt: '2024-03-14T09:30:00Z',
    completedAt: '2024-03-14T18:00:00Z',
    createdBy: '2',
  },
];